Ed-Fi-Alliance-OSS/Ed-Fi-ODS

Application/EdFi.Ods.Security/AuthorizationStrategies/NamespaceBased/NamespaceBasedAuthorizationStrategy.cs
Application/EdFi.Ods.Security/Claims/ClaimsIdentityProvider.cs
Application/EdFi.Ods.Tests/EdFi.Ods.Security/Authorization/NamespaceBasedAuthorizationTests.cs

This PR implements support for multiple prefixes for the standard data management resources.
It does not add support for multiple namespaces in Composite authorization.

[ODS-2980] Vendor access to multiple namespace prefixes

---

Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval Tests/GeneratedFileApprovalTests.Verify_All.ForScenario.Extensions.Homograph_Models_Entities_Entities.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval Tests/GeneratedFileApprovalTests.Verify_All.ForScenario.Extensions.Sample_Models_Entities_Entities.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval Tests/GeneratedFileApprovalTests.Verify_All.ForScenario.Extensions.TPDM_Models_Entities_Entities.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Mustache/Entities.mustache

Modified GetHashCode and Equals method implementation on entities to use case-insensitive checks for string values.
See also https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/pull/28.

[ODS-4296] Primary key conflict due to case sensitivity

---

Application/EdFi.Ods.Standard/Artifacts/Metadata/ApiModel.json
Application/EdFi.Ods.Standard/Artifacts/Schemas/Ed-Fi-Core.xsd
Application/EdFi.Ods.Standard/Artifacts/Schemas/Interchange-AssessmentMetadata.xsd
Application/EdFi.Ods.Standard/Artifacts/Schemas/Interchange-Descriptors.xsd
Application/EdFi.Ods.Standard/Artifacts/Schemas/Interchange-EducationOrgCalendar.xsd
Application/EdFi.Ods.Standard/Artifacts/Schemas/Interchange-EducationOrganization.xsd
Application/EdFi.Ods.Standard/Artifacts/Schemas/Interchange-Finance.xsd
Application/EdFi.Ods.Standard/Artifacts/Schemas/Interchange-MasterSchedule.xsd
Application/EdFi.Ods.Standard/Artifacts/Schemas/Interchange-Parent.xsd
Application/EdFi.Ods.Standard/Artifacts/Schemas/Interchange-PostSecondaryEvent.xsd
Application/EdFi.Ods.Standard/Artifacts/Schemas/Interchange-StaffAssociation.xsd
Application/EdFi.Ods.Standard/Artifacts/Schemas/Interchange-Standards.xsd
Application/EdFi.Ods.Standard/Artifacts/Schemas/Interchange-Student.xsd
Application/EdFi.Ods.Standard/Artifacts/Schemas/Interchange-StudentAssessment.xsd
Application/EdFi.Ods.Standard/Artifacts/Schemas/Interchange-StudentAttendance.xsd
Application/EdFi.Ods.Standard/Artifacts/Schemas/Interchange-StudentCohort.xsd
Application/EdFi.Ods.Standard/Artifacts/Schemas/Interchange-StudentDiscipline.xsd
Application/EdFi.Ods.Standard/Artifacts/Schemas/Interchange-StudentEnrollment.xsd
Application/EdFi.Ods.Standard/Artifacts/Schemas/Interchange-StudentGrade.xsd
Application/EdFi.Ods.Standard/Artifacts/Schemas/Interchange-StudentGradebook.xsd
Application/EdFi.Ods.Standard/Artifacts/Schemas/Interchange-StudentIntervention.xsd
Application/EdFi.Ods.Standard/Artifacts/Schemas/Interchange-StudentProgram.xsd
Application/EdFi.Ods.Standard/Artifacts/Schemas/Interchange-StudentTranscript.xsd
Application/EdFi.Ods.Standard/Artifacts/Schemas/Interchange-Survey.xsd
Application/EdFi.Ods.Standard/Artifacts/Schemas/SchemaAnnotation.xsd

Updates Core and Extensions based on MetaEd v2.2.1-dev.7, which includes bumping to v5.0.0 and removing the copyright header from the xsds.

[ODS-4370] Bring in MetaEd artifacts for release version change

---

Application/EdFi.Ods.Features/Resources/ChangeQueries.json

Adjusting metadata to match actual response for availableChangeVersions endpoint.

[ODS-4022] Ed-Fi ODS/API availableChangeQueries OpenApi Spec definition is incorrect

---

Application/EdFi.Ods.Api/Container/Modules/ExtensionsModule.cs

…m extensions (due to use of legacy API 'AppDomain.CurrentDomain.GetAssemblies').

[ODS-4659] Errors with TPDM entities

---

Artifacts/MsSql/Data/Security/1060-RemoveRedundantBootstrapPermissions.sql
Artifacts/PgSql/Data/Security/1060-RemoveRedundantBootstrapPermissions.sql

If  EXISTS (SELECT 1 FROM dbo.ResourceClaims WHERE ClaimName = claim_Name) AND EXISTS (SELECT 1 FROM dbo.ClaimSets WHERE ClaimSetName = claimSet_Name) then  clean up redundant security metadata for Bootstrap claim set.
we are not doing error handling here

[ODS-4379] Clean up redundant security metadata for Bootstrap claim set

---

Utilities/DataLoading/EdFi.LoadTools/ApiClient/TokenRetriever.cs

DefaultRequestHeaders is not thread safe
see: https://github.com/dotnet/runtime/issues/1500

[ODS-4852] Minimal Template Builds fails sometimes after merge of ODS-4788

---

Application/EdFi.Ods.Api/Startup/OdsStartupBase.cs

Removing embedded forced https redirect, will be handled by the host web server.

[ODS-4762] Refactor: remove HTTPS redirection

---

Utilities/DataLoading/EdFi.LoadTools/BulkLoadClient/Application/BulkLoadClientConfiguration.cs
Utilities/DataLoading/EdFi.LoadTools/BulkLoadClient/LoadProcess.cs

@jamessmckay @vimayya @plioi 
Please help review and merge the changes.
Changes:
1. Introduced new configuration parameter AdminAppSchemaAlreadyDownloaded to control the Xsd download from AdminApp
2. Refactored Xsd download steps, so can be called from Run and ValidateXmlFile methods.
3. On Run method calling LoadXsdFiles when AdminAppSchemaAlreadyDownloaded  is false.
Thanks

[AA-853] Enhance AA/ODS decoupling by using XSDs served up by ODS-4782

---

Application/EdFi.Ods.Common/Infrastructure/Configuration/NHibernateOdsConnectionProvider.cs

Added logic to wrap a failed `async` connection attempt in an DatabaseConnectionException.

[ODS-4875] API returns 500 rather than 401 status for descriptors requests from a snapshot that is not available

---

Artifacts/MsSql/Data/Security/1090-ManagedReasonNotTestedDescriptor.sql
Artifacts/PgSql/Data/Security/1090-ManagedReasonNotTestedDescriptor.sql

Adding security update scripts for MSSQL and PostgreSQL to change ReasonNotTestedDescriptor to be part of managedDescriptors, allowing Create/Update/Delete based on namespace.

[ODS-4957] Convert reasonNotTested into a managedDescriptor

---

Application/EdFi.Ods.Api/Helpers/AssemblyLoaderHelper.cs

Adding additional logging to assembly loading to ensure clear error messages if something fails to load.  Adding sni.dll to exclude list. Publishing to x64 now works correctly.

[ODS-4954] Publish doesn't work for target runtime win-x64

---

Utilities/GenerateSecurityGraphs/GenerateSecurityGraphs/FileDotEngine.cs
Utilities/GenerateSecurityGraphs/GenerateSecurityGraphs/Program.cs

Manually tested the next cases:
- --graphviz not specified and it is not installed ==> should download portable version
- --graphviz not specified and it is not installed and there is no internet connection ==> should show error message and exit
- --graphviz not specified and it is already installed in C:\Program Files\Graphviz ==> should use existing installation (don't download it)
- --graphviz not specified and portable version was previously downloaded ==> should not download it again
- --graphviz was specified and it is correct ==> should use it (don't download it)
- --graphviz was specified and it is invalid ==> should show error message and exit
- current directory is not the same as the executable path ==> should download portable version alongside the executable (not in the …

[ODS-5013] Security Visualization utility and Graphviz

---

Application/EdFi.Admin.DataAccess/EdFi.Admin.DataAccess.csproj
Application/EdFi.Ods.Api/EdFi.Ods.Api.csproj
Application/EdFi.Ods.Common/EdFi.Ods.Common.csproj
Application/EdFi.Ods.Repositories.NHibernate.Tests/EdFi.Ods.Repositories.NHibernate.Tests.csproj
Application/EdFi.Ods.Sandbox/EdFi.Ods.Sandbox.csproj
Application/EdFi.Ods.Tests/EdFi.Ods.Tests.csproj
Application/EdFi.Security.DataAccess/EdFi.Security.DataAccess.csproj
Application/EdFi.TestObjects/EdFi.TestObjects.csproj
Utilities/DataLoading/EdFi.BulkLoadClient.Console/EdFi.BulkLoadClient.Console.csproj
Utilities/DataLoading/EdFi.LoadTools.Test/EdFi.LoadTools.Test.csproj
Utilities/DataLoading/EdFi.LoadTools/EdFi.LoadTools.csproj
Utilities/DataLoading/EdFi.SmokeTest.Console/EdFi.SmokeTest.Console.csproj
Utilities/DataLoading/EdFi.XmlLookup.Console/EdFi.XmlLookup.Console.csproj
tests/EdFi.Admin.DataAccess.UnitTests/EdFi.Admin.DataAccess.UnitTests.csproj
tests/EdFi.Common.UnitTests/EdFi.Common.UnitTests.csproj
tests/EdFi.Ods.WebApi.CompositeSpecFlowTests/EdFi.Ods.WebApi.CompositeSpecFlowTests.csproj
tests/EdFi.Ods.WebApi.IntegrationTests/EdFi.Ods.WebApi.IntegrationTests.csproj
tests/EdFi.Security.DataAccess.UnitTests/EdFi.Security.DataAccess.UnitTests.csproj

Upgraded to 5.3.1v all projects that reference EdFi.Suite3.Common
After the PR is merged, I will check if the following packages need to be re-generated through TeamCity:
- EdFi.Admin.DataAccess
- EdFi.Common
- EdFi.LoadTools
- EdFi.Ods.Api
- EdFi.Ods.Common
- EdFi.Ods.Standard
- EdFi.Security.DataAccess

[ODS-5078] Update internal EdFi.Common package version

---

Application/EdFi.Ods.Common/Extensions/ValidatorExtensions.cs
Application/EdFi.Ods.Tests/EdFi.Ods.Common/Extensions/ObjectValidationExtensionsTests.cs
Application/EdFi.Ods.Tests/EdFi.Ods.Common/Extensions/ValidationExtensionsTests.cs

When sending an invalid calendarTypeDescriptoron the Calendar POST, a TargetInvocationException was being thrown, which then prevented the validation results from being returned by the API. Now we will catch this and then log the correct validation error.
Additionally, the Trace.Errors were swapped out for using log4net so that these types of messages could be seen in the WebApiLog.

ODS-5070 - Handle TargetInvocationException so correct validation results gets returned from api

---

Application/EdFi.Ods.Api/Startup/OdsStartupBase.cs

Remove Log4Net initialization since it is now initialized in EdFi.Ods.WebApi.Program.Main

[ODS-5097] Changing the default log location for the Web API running under IIS

---

Application/EdFi.Ods.Sandbox/Provisioners/SqlServerSandboxProvisioner.cs

To test Docker MsSql scenario follow the next steps:
1) Run `initdev` in the host machine
2) Configure SQL Server env vars (.env); There were some renames during this Docker release so you might need to update it (check https://techdocs.ed-fi.org/pages/viewpage.action?spaceKey=EDFITOOLS&title=Docker+Deployment+v2.1)
3) Test that your SQL Server instance allows remote access; Using management studio try to connect to your local ip address (don't use `localhost`); and use SQL Server Auth.
4) Bring Docker Compose up and test Sandbox Admin (create a sandbox)

[ODS-5203] Sandbox Admin is unable to create sandboxes under Docker pointing to SQL Server hosted on Windows

---

Application/EdFi.Ods.Api/Models/GraphML/ResourceLoadOrder.cs
Application/EdFi.Ods.Features/Controllers/AggregateDependencyController.cs
tests/EdFi.Ods.WebApi.IntegrationTests/Sandbox/Controllers/AggregateDependencyControllerTests.Should_Get_Dependencies.approved.txt

Previously everything was output in the correct order, but with only a "Create" operation and no "Updates". Now this fixes it so that the graph results will include both possible operations, and then when needed, split out "Create" and "Update" based on any resources that have to be created before an update can be performed. With these changes the following order of resources should be observed in the output from this endpoint:
- Student Create / Parent Create
- StudentSchoolAssociation Create/Update
- StudentParentAssociation Create/Update
- Student Update / Parent Update
- StaffEducationOrganizationEmploymentAssociations Create/Update
- StaffEducationOrganizationAssignmentAssociations Create/Update
For additional information about this endpoint, please [see this Tech Docs …

ODS-5186 - Update Dependencies to include Updates operation and ensure resources are output in correct operational order

---

Artifacts/MsSql/Data/Security/0001-ResourceClaimMetadata_generated.sql
Artifacts/PgSql/Data/Security/0001-ResourceClaimMetadata_generated.sql
Postman Test Suite/Record Ownership Test/Ed-Fi ODS-API Record Ownership Test Suite.postman_collection.json
Postman Test Suite/Record Ownership Test/Record Ownership Manual Setup Scripts.sql
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/ApprovalTests.Verify_All.ForScenario.Artifacts_MsSql_Data_Security_0001-ResourceClaimMetadata_generated.approved.sql
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/ApprovalTests.Verify_All.ForScenario.Artifacts_PgSql_Data_Security_0001-ResourceClaimMetadata_generated.approved.sql
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Mustache/ResourceClaimMetadata.mustache
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Mustache/ResourceClaimMetadata.pgsql.mustache

Use case for Record Ownership Testing using School and StudentSectionAssociation  resource
--Client 1 should be able to full CRUD their School 1.
--Resource -Client 1 has full CRUD - School 1
--Client 2 should be able to full CRUD School 2.
-- Resource -Client 2 has full CRUD - School 2
--Assuming Client 2 is assigned the extra ownership token, it should also be able to full CRUD School 1. 
--But Client 1, without the assignment to Ownership Token 2, should not be able to CRUD School 2.

[ODS-5221] Add Postman tests for Record Ownership feature

---

Application/EdFi.Ods.Api/EdFi.Ods.Api.csproj
Application/EdFi.Ods.Common/EdFi.Ods.Common.csproj
Application/EdFi.Ods.Repositories.NHibernate.Tests/EdFi.Ods.Repositories.NHibernate.Tests.csproj
Application/EdFi.Ods.Standard/EdFi.Ods.Standard.csproj
Application/EdFi.Ods.Tests/EdFi.Ods.Tests.csproj
tests/EdFi.Ods.WebApi.CompositeSpecFlowTests/EdFi.Ods.WebApi.CompositeSpecFlowTests.csproj
tests/EdFi.Ods.WebApi.IntegrationTests/EdFi.Ods.WebApi.IntegrationTests.csproj

Part of the .NET6 upgrade also updated the Nhibernate package, and once upgraded, there were TypeExceptions being thrown on a number of smoke tests and Repository tests. Downgrading back to the previous version fixes this. Another ticket will be opened to investigate what is needed to get the latest version of NHibernate working.
With ODS-5242 still being under review in PR #424  not all tests will be working on this branch, but if you apply its commits to this branch and do the same for the ODS-Implementation repo, you should see everything working.

ODS-5273 - Downgrade Nhibernate to previous version from before net6 upgrade

---

Application/EdFi.Ods.Features/Controllers/DeletesController.cs
Postman Test Suite/Ed-Fi ODS-API ChangeQueries Test Suite.postman_collection.json
Postman Test Suite/Ed-Fi ODS-API Integration Test Suite AuthorizationTests Multiple Key-Secrets.postman_collection.json
Postman Test Suite/Ed-Fi ODS-API Integration Test Suite AuthorizationTests.postman_collection.json
Postman Test Suite/Ed-Fi ODS-API Integration Test Suite Multiple Edorg types.postman_collection.json

Tests were failing for two reasons:
1. A null reference exception on missing data not being in the requests. Adding the new needed information got these tests passing.
2. A routing precedence change occurred in the latest update, so an ordering had to be set on the deletes endpoint to ensure they are done in the right order
Please not that other tests will still be failing on this build and will be handled by later tickets, but the postman tests should all be passing.

ODS-5242 - Update postman test request data to fix tests

---

Utilities/SdkGen/EdFi.SdkGen.Console/EdFi.SdkGen.Console.csproj

Also updated nuget packages to match versions they were updated to in other projects. Latest log4net is now 2.0.14, but since other projects were updated to 2.0.13, it was updated only to that version.
No updates were needed to the implementation repo since all the relevant packages pull "latest"

ODS-5246 - Update SDKGen to target net6

---

Utilities/DataLoading/EdFi.BulkLoadClient.Console/EdFi.BulkLoadClient.Console.csproj
Utilities/DataLoading/EdFi.LoadTools.Test/JsonMetadataTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/MappingFactories/LookupToGetByExampleMetadataMappingFactoryTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/MappingFactories/LookupToIdentityMetadataMappingFactoryTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/MappingFactories/ResourceToIdentityMetadataMappingFactoryTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/MappingFactories/ResourceToResourceMetadataMappingFactoryTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/OAuthTokenHandlerTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/ReadMe.md
Utilities/DataLoading/EdFi.LoadTools.Test/SmokeTests/ModelDependencySortTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/SwaggerRetrieverTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/XsdFileRetrieverTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/XsdMetadataRetrievalTests.cs
Utilities/DataLoading/EdFi.LoadTools/EdFi.LoadTools.csproj
Utilities/DataLoading/EdFi.LoadTools/Engine/HashProvider.cs
Utilities/DataLoading/EdFi.LoadTools/SmokeTest/PropertyBuilders/BaseBuilder.cs
Utilities/DataLoading/EdFi.SmokeTest.Console/EdFi.SmokeTest.Console.csproj
Utilities/DataLoading/EdFi.XmlLookup.Console/EdFi.XmlLookup.Console.csproj

In addition to updating it to NET6, the test cases that are for running manually had to be renamed to remove the space, since there is a current [bug](https://github.com/nunit/nunit3-vs-adapter/issues/876) in the NUnit Test Adapter causing filtering to not work on categories with spaces in them.
A related PR that has now been merged updated the Kotlin builds for the load tools [here](https://github.com/Ed-Fi-Alliance/Ed-Fi-TeamCity-Configs/pull/44) to update the build step to match the change from 'Run Manually' to 'RunManually'.
A successful build after that related PR was merged can be found [here](https://intedfitools1.msdf.org/buildConfiguration/OdsPlatform_OdsImplementationKotlin_EdFiLoadTools_BranchBuild/153248)

ODS-5250 - Update DataLoading to NET6

---

Application/EdFi.Ods.Api/Security/AuthorizationStrategies/Relationships/RelationshipsWithStudentsOnlyThroughResponsibilityAuthorizationStrategyFilterConfigurator.cs

Fixed a bug in the filter definition for the RelationshipsWithStudentsThroughResponsibility so that the StudentUSI (instead of the SourceEducationOrganizationId) column of the auth view is used to join to the StudentUSI in the subject.
JOIN clause _before_ change:
```sql
-- Authorization Strategy: RelationshipsWithStudentsOnlyThroughResponsibility
LEFT OUTER JOIN auth.EducationOrganizationIdToStudentUSIThroughResponsibility authviewde3_ 
ON  ( this_.StudentUSI = authviewde3_.SourceEducationOrganizationId )
```
JOIN clause _after_ change:
```sql
-- Authorization Strategy: RelationshipsWithStudentsOnlyThroughResponsibility
LEFT OUTER JOIN auth.EducationOrganizationIdToStudentUSIThroughResponsibility authview21x3_
ON  ( this_.StudentUSI = authview21x3_.StudentUSI )
```
WHERE clause _before_ …

[ODS-5301] Authorization simplifications to filtering architecture to take advantage of EducationToEducationOrganizationId table (bugfix)

---

tests/EdFi.Ods.WebApi.CompositeSpecFlowTests/CompositeResourcesCanBeDefinedThroughXmlFeature.CompositeIncludesLinkedCollectionWithProperties.approved.txt

This test was previously being ignored when changes to the auth filtering was made so it did not show up as failing until the PR that removed the ignore was merged. Now this test will filter the query using ClaimEdOrgIds instead of LEAId. The alias was also updated along with fixing the indention to match what is generated, which lines up with other approved files as well in how far the subquery is indented.

ODS-5301 - Update composite test to use ClaimEdOrg filtering

---

Application/EdFi.Admin.DataAccess/EdFi.Admin.DataAccess.csproj
Application/EdFi.Common/EdFi.Common.csproj
Application/EdFi.Ods.Api/EdFi.Ods.Api.csproj
Application/EdFi.Ods.Common/EdFi.Ods.Common.csproj
Application/EdFi.Ods.Repositories.NHibernate.Tests/EdFi.Ods.Repositories.NHibernate.Tests.csproj
Application/EdFi.Ods.Sandbox/EdFi.Ods.Sandbox.csproj
Application/EdFi.Ods.Tests/EdFi.Ods.Tests.csproj
Application/EdFi.Security.DataAccess/EdFi.Security.DataAccess.csproj
Application/EdFi.TestObjects/EdFi.TestObjects.csproj
Application/Test.Common/Test.Common.csproj
Utilities/DataLoading/EdFi.BulkLoadClient.Console/EdFi.BulkLoadClient.Console.csproj
Utilities/DataLoading/EdFi.LoadTools.Test/EdFi.LoadTools.Test.csproj
Utilities/DataLoading/EdFi.LoadTools/EdFi.LoadTools.csproj
Utilities/DataLoading/EdFi.SmokeTest.Console/EdFi.SmokeTest.Console.csproj
Utilities/DataLoading/EdFi.XmlLookup.Console/EdFi.XmlLookup.Console.csproj
tests/EdFi.Admin.DataAccess.UnitTests/EdFi.Admin.DataAccess.UnitTests.csproj
tests/EdFi.Ods.WebApi.CompositeSpecFlowTests/EdFi.Ods.WebApi.CompositeSpecFlowTests.csproj
tests/EdFi.Ods.WebApi.IntegrationTests/EdFi.Ods.WebApi.IntegrationTests.csproj
tests/EdFi.Security.DataAccess.UnitTests/EdFi.Security.DataAccess.UnitTests.csproj

Cannot write DateTime with Kind=UTC to PostgreSQL type 'timestamp without time zone', consider using 'timestamp with time zone'. Note that it's not possible to mix DateTimes with different Kinds in an array/range. See the Npgsql.EnableLegacyTimestampBehavior AppContext switch to enable legacy behavior.
I was getting above error after upgrading to Npgsql package to "6.0.3"  .Basically posgreSQl default to timestamp with time zone  now So I added additional code to make it work like before with  AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);
And then it will use timestamp without time zone for ClientAccessToken class - Expiration property for example here
Reference Links
https://stackoverflow.com/questions/70643895/how-to-say-datetime-timestamp-without-time-zone-in-ef-co …

[ODS-5247] Update Npgsql and HealthChecks libraries

---

Application/EdFi.Admin.DataAccess/Contexts/UsersContext.cs
Application/EdFi.Admin.DataAccess/Utils/ValidateDatabase.cs
Application/EdFi.Ods.Api/EdFi.Ods.Api.csproj
Application/EdFi.Ods.Api/Middleware/EdFiOAuthAuthenticationHandler.cs
Application/EdFi.Ods.Repositories.NHibernate.Tests/EdFi.Ods.Repositories.NHibernate.Tests.csproj
Application/EdFi.Ods.Sandbox/EdFi.Ods.Sandbox.csproj
Application/EdFi.Ods.Tests/EdFi.Ods.Tests.csproj
Application/EdFi.Security.DataAccess/Contexts/SecurityContext.cs
Application/EdFi.Security.DataAccess/Repositories/CachedSecurityRepository.cs
Application/EdFi.Security.DataAccess/Repositories/SecurityRepository.cs
Application/EdFi.Security.DataAccess/Repositories/SecurityRepositoryBase.cs
Application/EdFi.Security.DataAccess/Utils/ResettableLazy.cs
Application/EdFi.Security.DataAccess/Utils/ValidateDatabase.cs
Application/Test.Common/Test.Common.csproj
tests/EdFi.Ods.WebApi.CompositeSpecFlowTests/EdFi.Ods.WebApi.CompositeSpecFlowTests.csproj
tests/EdFi.Ods.WebApi.IntegrationTests/EdFi.Ods.WebApi.IntegrationTests.csproj
tests/EdFi.Security.DataAccess.UnitTests/Repositories/CachedSecurityRepositoryTests.cs

There are 2 main changes in this PR:
1. Fix the database initializers to throw an error if the databases don't exist instead of trying to create them (see comments below).
2. Since the `SecurityRepository` hit the database in the constructor, if the database was invalid the error message was encapsulated in a `DependencyResolutionException` (from Autofac). This made the error a bit cryptic so I added lazy initialization to the repository.

[ODS-5298] Improve Error Reporting for Bad Connection String

---

Utilities/GenerateSecurityGraphs/GenerateSecurityGraphs/Models/AuthorizationMetadata/ActionAndStrategy.cs
Utilities/GenerateSecurityGraphs/GenerateSecurityGraphs/Models/AuthorizationMetadata/EffectiveActionAndStrategy.cs
Utilities/GenerateSecurityGraphs/GenerateSecurityGraphs/Models/AuthorizationMetadata/Resource.cs
Utilities/GenerateSecurityGraphs/GenerateSecurityGraphs/Program.cs

Changes included in this PR:
- To support multiple authorization strategies, I changed `string` to `HashSet<string>` where appropriate
- Removed dead code
- Removed obsolete comments
- Renamed `Resource.Name` to `Resource.ClaimName` and other miscellaneous renames
- Changed `WebClient` to `HttpClient` (since `WebClient` is now deprecated) to download Graphviz
- Changed explicitly typed variables to implicit
- Changed LINQ query expressions to method chaining

[ODS-5259] Update security visualization tool to visualize multiple auth strategies

---

.github/workflows/manual.yml
.github/workflows/pullrequest.yml
.github/workflows/shared.yml
build.ps1

This creates two new GithubActions, one workflow that can be manually triggered and a second that gets triggered on a pull request to main. The manually triggered one mimics what exists in TeamCity right now to build, test, pack, and publish, while the pull request one will only run a build and test.
You will not see the ability to manually run the github workflow since it has to exist in main first before it will show up there, so to test these workflows out I forked ODS, applied the workflows in the main branch and then tested them there in the fork. But you will be able to see the pull request workflow building and passing as part of the checks here.
You will also notice how 10 is being added to the run number for determining the revision in the version for packing and publishing. This …

ODS-5303 - Move Admin.DataAccess build to GithubActions

---

.github/workflows/shared.yml

Without this env variable, nuget publishing fails.
Also to keep this consistent with other Github Actions that has been setup, the Azure Artifact Url has been moved to a secret that is shared in the org.
For more information around why this is needed, you can see it referenced in the documentation [here](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/dotnet-exe?view=azure-devops#restore-nuget-packages)

ODS-5303 - Add env var needed for Nuget publishing to Azure in Github Action

---

.github/workflows/shared.yml

This Org does not have a secret for storing it, and it is not something that changes often so it can be in hard coded here. 
In the previous run after the code was merged you can see the error message that says -k is not a valid source. 
This was because there was no secret defined in this org, and -k would have been the next value to parse as part of the dotnet nuget push command as you can see here:
`dotnet nuget push $packagePath -s $env:AZURE_ARTIFACT_URL -k $env:AZURE_ARTIFACT_NUGET_KEY --force-english-output`
Which with an empty `AZURE_ARTIFACT_URL ` would have evaluated as:
`dotnet nuget push EdFi.Suite3.Admin.DataAccess.5.4.11.nupkg -s -k nuget_key_here --force-english-output`

ODS-5303 - Use hard coded Azure Artifact URL

---

.github/workflows/shared.yml

You cannot reference one env var from inside another like we were trying before, so the nuget feed url has to be hard coded.
Looking at the [previous run](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/actions/runs/2036441852), you can see it does not know how to parse `env` when parsing environment variables.

ODS-5303 Use hard coded url instead of env var

---

.github/workflows/shared.yml

This provider is needed to take advantage of the env var `VSS_NUGET_EXTERNAL_FEED_ENDPOINTS` that stores the credentials that are used when publishing to Azure Artifacts.

ODS-5303 - Install artifact credential provider to authenticate to Azure Artifacts

---

.github/workflows/shared.yml
build.ps1

Doing it this way instead of referencing the env vars directly in the build script. This more matches what the existing Data Import Github Actions workflows do, which work.

ODS-5303 - Pass env variables to build script as parameters

---

Application/EdFi.Ods.Api/Controllers/TokenController.cs
Application/EdFi.Ods.Api/Providers/ClientCredentialsTokenRequestProvider.cs
Application/EdFi.Ods.Tests/EdFi.Ods.Api/Controllers/TokenControllerTests.cs
Application/EdFi.Ods.Tests/EdFi.Ods.Api/Controllers/TokenControllerUsingJsonTests.cs

Steps to reproduce :  Follow this document https://techdocs.ed-fi.org/pages/viewpage.action?spaceKey=ODSAPIS3V54&title=How+To%3A+Load+the+ODS+with+Sample+XML+Data+using+Bulk+Load+Client+Utility
In Step 7 : you can change invalid key/secret . 
you can test this code change using EdFi.BulkLoadClient.Console
{
"profiles": {
"EdFi.BulkLoadClient.Console": {
"commandName": "Project",
"commandLineArgs": "-b \"http://localhost:54746/\"  -y 2022  -data \"C:\\Ed-Fi-SampleDataLoad\\Sample XML\" -e \"tpdm\" -w \"C:/Ed-Fi-SampleDataLoad/Working/\"  -k empty1 -s emptySecret1  -r \"1\" -l \"1\" -f"
}
}
}
After this code change , you will get 401 (Unauthorized) error instead of 400 (Bad Request) as per acceptance criteria 
242570 ERROR OdsRestClient - Unexpected Exception on resource post …

ODS-4997 Wrong HTTP response when bulk uploading descriptors with invalid key and secret

---

Application/EdFi.Ods.Api/EdFi.Ods.Api.csproj
Application/EdFi.Ods.Api/IdentityValueMappers/FluentValidationPutPostRequestResourceValidator.cs
Application/EdFi.Ods.Api/Validation/DescriptorNamespaceValidator.cs
Application/EdFi.Ods.Common/EdFi.Ods.Common.csproj
Application/EdFi.Ods.Common/Validation/FluentValidationObjectValidator.cs
Application/EdFi.Ods.Profiles.Test/EdFi.Ods.Profiles.Test.csproj
Application/EdFi.Ods.Tests/EdFi.Ods.Tests.csproj
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/EdFi.Ods.CodeGen.Tests.csproj
Utilities/CodeGeneration/EdFi.Ods.CodeGen/EdFi.Ods.CodeGen.csproj
Utilities/VisualStudioProjectTemplates/EdFi.ProjectTemplates.Profiles/Template_Project.csproj
tests/EdFi.Ods.WebApi.CompositeSpecFlowTests/EdFi.Ods.WebApi.CompositeSpecFlowTests.csproj

For this PR, FluentValidation was updated to the latest version on Nuget, and minor changes were made to the code based on breaking changes introduced between 8.6.3 and 10.4.0, which were:
- Referencing the Global ValidatorOptions for CascadeMode
- Removed usage of non-generic Validator and ValidationContext per the [upgrade guidelines](https://docs.fluentvalidation.net/en/latest/upgrading-to-9.html#removal-of-non-generic-validate-overload) 
- Change from CascadeMode.StopOnFirstFailure to Stop since StopOnFirstFailure is [now marked as Obsolete](https://docs.fluentvalidation.net/en/latest/conditions.html#stop-vs-stoponfirstfailure) and adding Stop per field instead of globally matches how StopOnFirstFailure worked before
Related PRs: …

[ODS-5254] - Update FluentValidation to 10.x

---

.github/workflows/edFi.admin.dataaccess manual.yml
.github/workflows/edFi.admin.dataaccess pullrequest.yml
.github/workflows/edFi.loadtools manual.yml
.github/workflows/edFi.loadtools pullrequest.yml
.github/workflows/edFi.security.dataaccess manual.yml
.github/workflows/edFi.security.dataaccess pullrequest.yml
.gitignore
Utilities/DataLoading/EdFi.LoadTools.Test/UtilitiesTests.cs
build.ps1

This is similar to previous additions where EdFi.Admin.DataAccess and EdFi.Security.DataAccess was moved from TeamCity to Github.
Two additional changes made as part of this work were:
- Removing the PackageName script parameter from being required, since the build and test steps of the script do not need them and only the pack and publish did.
- Adding a test category filtering parameter for the test step. The LoadTools build skipped the RunManually tests so a way to do that here was needed as well.
Due to an existing issue, [ODS-5391](https://tracker.ed-fi.org/browse/ODS-5391) the test step of the builds will fail right now. So you can either:
1. Comment out `MappingTests_for_EdFi_models()` in MapperTests OR
2. Make the following changes to the JSON for the test to get it passing, which …

[ODS-5350] - Move LoadTools builds to GithubActions

---

.github/workflows/edFi.loadtools manual.yml

They were previously looking in Ed-Fi-Ods\ but that is this repo, so that part needed to be removed.

[ODS-5350] - Update to use correct project file paths for Load Tools in Github Actions

---

.github/workflows/edFi.loadtools manual.yml

In Github Workflow it was missing the dot, so it created and published to Azure Artifacts a package named `EdFi.Suite3.SmokeTestConsole` instead of `EdFi.Suite3.SmokeTest.Console`

[ODS-5350] Update SmokeTest package name to match existing packages

---

.github/workflows/edFi.loadtools manual.yml

Like the pack step previously, it was missing the dot in the name, so when it tried to publish now that the dot was added, it failed to find the package.

[ODS-5350] - Fix LoadTools publish step to use correct name for smoke test client

---

Utilities/DataLoading/EdFi.LoadTools/Common/EdFiConstants.cs
Utilities/DataLoading/EdFi.LoadTools/SmokeTest/PropertyBuilders/DescriptorPropertyBuilder.cs
Utilities/DataLoading/EdFi.LoadTools/SmokeTest/PropertyBuilders/NamespacePropertyBuilder.cs
Utilities/DataLoading/EdFi.SmokeTest.Console/SmokeTestsDestructiveSdkModule.cs

There is already a `PropertyBuilder` responsible for initializing namespaces; however, it was limited to properties of _Descriptors_. I have removed this filter, so it now initializes all properties that require a namespace.
To ensure that this change didn't affect other cases, I compared the logs before and after the change.

[ODS-5317] Fix destructive Smoke Test errors related to unauthorized namespace access

---

.github/workflows/edFi.ods.common manual.yml
.github/workflows/edFi.ods.common pullrequest.yml
Application/EdFi.Ods.Common/EdFi.Ods.Common.sln
Application/EdFi.Ods.Common/EdFi.Ods.Common.sln.DotSettings
Application/EdFi.Ods.Common/EdFi.Ods.Common.sln.licenseheader
build.ps1

In addition to adding these two new workflows a new solution file, dotsettings file, and license update file was added so that the build script could call the solution file instead of a project file.
Additionally you will notice that the manual workflow specifies a `BUILD_INCREMENTER` but the pull request workflow does not. This is because we need the incrementer for the manual workflow since it packages up the build and we need its packages to not overlap with the ones from TeamCity, but the pull request workflow does not package up anything so it does not need the incrementer.

[ODS-5352] Add new workflows for Edfi.Ods.Common

---

Application/EdFi.Ods.Api/EdFi.Ods.Api.csproj
Application/EdFi.Ods.Repositories.NHibernate.Tests/EdFi.Ods.Repositories.NHibernate.Tests.csproj
Application/EdFi.Ods.Tests/EdFi.Ods.Tests.csproj
Application/Test.Common/Test.Common.csproj
Postman Test Suite/Ed-Fi ODS-API Multiple Authorization Strategy Test Suite.postman_collection.json
tests/EdFi.Ods.WebApi.CompositeSpecFlowTests/EdFi.Ods.WebApi.CompositeSpecFlowTests.csproj
tests/EdFi.Ods.WebApi.IntegrationTests/EdFi.Ods.WebApi.IntegrationTests.csproj

All that was needed was updating the edfi.suite3.security.dataaccess package since the one being referenced before (6.0.11) was built from a branch and not main, and was from before all of the multiple auth changes were made.
Additionally while looking at the tests it was found that all the cleanup was not being done and the students were not being deleted, so the test was updated to do that as part of the cleanup.

[ODS-5434] - Fix Multiple Auth postman test failures

---

Postman Test Suite/Ed-Fi ODS-API Multiple Authorization Strategy Test Suite.postman_collection.json

Generally, this test suite was very close to our Postman style guidelines, just needed to:
- Renamed collection `Initial Setup` to `Setup`
- Renamed collection `Clean Up Test Data` to `Teardown`
- Removed collection `Multiple Authorization Strategy` since the parent suite already has the feature's name.
- Added format to some Pre-request Scripts and Test scripts
Note that GitHub's diff algorithm detects too many changes, use VS Code to get a clearer diff.

[ODS-5407] Update guidance for writing effective Postman tests

---

Application/EdFi.Ods.Features/ChangeQueries/Controllers/SnapshotsController.cs
Application/EdFi.Ods.Features/ChangeQueries/Repositories/Snapshots/GetSnapshots.cs
Application/EdFi.Ods.Features/ChangeQueries/Repositories/Snapshots/IGetSnapshots.cs
Application/EdFi.Ods.Features/ChangeQueries/Repositories/TrackedChangesResourceDataProviderBase.cs
Application/EdFi.Ods.Features/Resources/ChangeQueries.json

The /snapshots endpoint can now return the total-count and respects the defaultPageSizeLimit defined in appsettings.

[ODS-5293] Change query delete endpoint paging

---

.github/workflows/CodeQL Security Scan.yml
Application/EdFi.Ods.Profiles.Test/Profiles.xml
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/ApprovalTests.Verify_All.ForScenario.Profiles.Test_Controllers_Controllers.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/ApprovalTests.Verify_All.ForScenario.Profiles.Test_Pipelines_CreateOrUpdatePipelines.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/ApprovalTests.Verify_All.ForScenario.Profiles.Test_Requests_Requests.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Generators/Resources/ResourceCollectionRenderer.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Generators/Resources/ResourceProfileData.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Helpers/CodeRepositoryHelper.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Metadata/ProfileMetadataValidator.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Mustache/Resources.mustache

Fixed code generation issue where when a reference which has unified key properties is included, while the other reference(s) are not included, compilation would fail due to the missing private "implicit" reference artifacts.

[ODS-5601] Issues to do with Profiles on TEA project (only some references with unified key included)

---

Utilities/CodeGeneration/EdFi.Ods.CodeGen/Generators/Resources/ResourceProfileData.cs

Resources that come from an implicit extension don't have an Entity (Resource.Entity = null), so we shouldn't use Entity equality comparer.
Note that this issue cannot be reproduced with Sample's implicit extension _StudentEducationOrganizationAssociationStudentCharacteristicExtension_ since that's the only implicit extension in _StudentEducationOrganizationAssociationStudentCharacteristic_, so FirstOrDefault succeeds. To reproduce it, there must be at least 2 implicit extensions for a given resource.
If GetContainedResource fails to find a matching Resource then [IsIncluded](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/blob/main/Utilities/CodeGeneration/EdFi.Ods.CodeGen/Generators/Resources/Resources.cs#L555) returns false, so the Collection instantiation doesn't get rendered and …

[ODS-5601] Issues to do with Profiles on TEA project - Issue no. 2

---

Application/EdFi.Ods.Features/OpenApiMetadata/Factories/OpenApiMetadataDocumentHelper.cs
Application/EdFi.Ods.Features/OpenApiMetadata/Models/OpenApiMetadataDocument.cs

Now when the metadata is generated, any nullable properties will have x-nullable: true added like this:
```
"disciplineActionLength": {
"description": "The length of time in school days for the discipline action (e.g. removal, detention), if applicable.",
"format": "double",
"x-nullable": true,
"type": "number"
},
```
Which results in the generated sdk marking the property as nullable and setting EmitDefaultValue as true like this:
```
[DataMember(Name = "disciplineActionLength", EmitDefaultValue = true)]
public double? DisciplineActionLength { get; set; }
```
For any properties that are not nullable, this new x-nullable property will not show up in the metadata, and therefor will not have EmitDefaultValue = true, for example, DisciplineDate on StudentDiscipplineAction will look like this …

ODS-5608 - Add x-nullable property to metadata for nullable properties

---

.github/workflows/Packages - EdFi.Database.Admin.yml
.github/workflows/Packages - EdFi.Database.Security.yml
Artifacts/MsSql/Data/Security/2100-UpdateClaimSetInternalUseOnlyColum.sql

This added a new workflow for building and publishing the EdFi.Database.Security packages:
EdFi.Database.Security
EdFi.Database.Security.BACPAC
EdFi.Database.Security.PostgreSQL
Additionally, the EdFi.Database.Admin workflow was cleaned up to use pwsh, fix paths for use in linux, remove manual workflow dispath inputs, use the new Powreshell script for checking out the right branch, and added the publish step that was not in there before (due to it originally running against Postgres14).
If you look at the commit `Cleanup Database.Admin workflow` that is where you will be able to see the successful building and publishing of the packages for both of these workflows.

ODS-5549 - Move EdFi.Database.Security build to Github Actions

---

Application/EdFi.Ods.Api/Startup/OdsStartupBase.cs

This is similar to what we already do in Sandbox and Swagger projects. Currently [we are configured](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/blob/main/Application/EdFi.Ods.Api/Startup/OdsStartupBase.cs#L199) to only forward the following already:
- XForwardedFor
- XForwardedHost
- XForwardedProto
So if more need to be forwarded an additional code change would be needed.

ODS-5625 - Use Forwarded Headers in API when configured to use reverse proxy headers

---

Utilities/DataLoading/EdFi.LoadTools/Engine/Constants.cs
Utilities/DataLoading/EdFi.LoadTools/Mapping/Mapper.cs
Utilities/DataLoading/EdFi.LoadTools/Mapping/MapperConfigurationExpression.cs

The smoke tests use fuzzy search to know how to map properties from the EvaluationRating into the needed EvaluationRatingReference in EvaluationObjectiveRatings.
The fuzzy search constructs candidates separating them with '\\', for example, to resolve EvaluationRatingReference\PersonId, a candidate is `EvaluationRating\PerformanceEvaluationRatingReference\PersonId`, another candidate is `EvaluationRating\Reviewers\PersonId`, and a score is given to each candidate based on how similar the paths are. The candidate with the highest score gets used.
In Linux, the directory separator char is '/' which is treated differently by the [method ](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/blob/66d976f8922ac0f75324a1cdc7c04d06b2e44143/Utilities/DataLoading/EdFi.LoadTools/Engine/ExtensionMethods.c …

[ODS-5662] DestructiveSdk smoke tests fail if executed from Linux

---

Application/EdFi.Ods.Api/Caching/DescriptorsCache.cs
Application/EdFi.Ods.Tests/EdFi.Ods.Api/Caching/DescriptorsCacheTests.cs

Added tests for the following scenarios:
1. A cache miss when the descriptor cache is empty (uninitialized)
2. A cache miss with an INVALID descriptor value
3. A cache miss with a newly added descriptor value

[ODS-5680] Descriptor cache performs full refresh with a cache miss

---

Application/EdFi.Ods.Api/Security/Authorization/Repositories/RepositoryOperationAuthorizationDecoratorBase.cs
Application/EdFi.Ods.Api/Security/AuthorizationStrategies/Relationships/Filters/PostgresViewBasedSingleItemAuthorizationQuerySupport.cs
Application/EdFi.Ods.Api/Security/AuthorizationStrategies/Relationships/Filters/SqlServerViewBasedSingleItemAuthorizationQuerySupport.cs
Postman Test Suite/Ed-Fi ODS-API Integration Test Suite AuthorizationTests.postman_collection.json

Fix SQL used for authorization so that it returns no results rather than cause runtime error due to SQL syntax error.

[ODS-5664] Relationship-based authorization of PUT/POST/DELETE requests returns 500 status for API client with no ed orgs

---

Application/EdFi.Ods.Common/Infrastructure/Repositories/CreateEntity.cs
Application/EdFi.Ods.Tests/EdFi.Ods.Common/Infrastructure/Repositories/CreateEntityTests.cs

This issue is present with all Resources with a string Id. Id's with numeric types return expected values.

[ODS-5318] Server error when posting new EducationContent with no contentIdentifier

---

.github/workflows/Pkg EdFi.Ods.Minimal.Template.PostgreSQL.yml
.github/workflows/Pkg EdFi.Ods.Minimal.Template.TPDM.PostgreSQL.yml
.github/workflows/Pkg EdFi.Ods.Minimal.Template.TPDM.yml
.github/workflows/Pkg EdFi.Ods.Minimal.Template.yml
.github/workflows/Pkg EdFi.Ods.Populated.Template.PostgreSQL.yml
.github/workflows/Pkg EdFi.Ods.Populated.Template.TPDM.PostgreSQL.yml
.github/workflows/Pkg EdFi.Ods.Populated.Template.TPDM.yml
.github/workflows/Pkg EdFi.Ods.Populated.Template.yml

Any code Changes to scripts in https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/tree/main/DatabaseTemplate/Modules possibly need template run and definitely handled by  manual run of [Rebuild Database Templates.yml](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/blob/main/.github/workflows/Rebuild%20Database%20Templates.yml)  .so removing Trgr EdFi.Ods.DB.Templates workflow in ODS repo workflow

[ODS-5732] Trgr EdFi.Ods.DB.Templates workflow in ODS repo removed

---

Application/EdFi.Ods.Api/ExceptionHandling/Translators/SqlServer/DuplicateNaturalKeyCreateExceptionTranslator.cs
Application/EdFi.Ods.Tests/EdFi.Ods.Api/ExceptionHandling/Translators/SqlServer/DuplicateNaturalKeyCreateExceptionTranslatorTests.cs
Application/EdFi.Ods.Tests/EdFi.Ods.Api/ExceptionHandling/Translators/SqlServer/TestModels/GeneralStudentProgramAssociation.json

To test this change, make a POST request to the StudentProgramAssociations endpoint with the following payload
```
{
"educationOrganizationReference": {
"educationOrganizationId": 255901
},
"programReference": {
"educationOrganizationId": 255901,
"programName": "Career and Technical Education",
"programTypeDescriptor": "uri://ed-fi.org/ProgramTypeDescriptor#Career and Technical Education"
},
"studentReference": {
"studentUniqueId": "604822"
},
"beginDate": "2021-08-30",
"endDate": "2021-12-17",
"reasonExitedDescriptor": "uri://ed-fi.org/ReasonExitedDescriptor#Reached maximum age",
"programParticipationStatuses": [],
"ctePrograms": [],
"cteProgramServices": [],
"services": []
}
```

[ODS-4229] Improve Error Message for Sub Class Key Collision

---

.github/workflows/Cleanup Caches by a branch.yml
.github/workflows/CodeQL Security Scan.yml
.github/workflows/Lib edFi.admin.dataaccess manual.yml
.github/workflows/Lib edFi.admin.dataaccess pullrequest.yml
.github/workflows/Lib edFi.common manual.yml
.github/workflows/Lib edFi.common pullrequest.yml
.github/workflows/Lib edFi.loadtools manual.yml
.github/workflows/Lib edFi.loadtools pullrequest.yml
.github/workflows/Lib edFi.ods.api manual.yml
.github/workflows/Lib edFi.ods.api pullrequest .yml
.github/workflows/Lib edFi.ods.common manual.yml
.github/workflows/Lib edFi.ods.common pullrequest.yml
.github/workflows/Lib edFi.ods.standard manual.yml
.github/workflows/Lib edFi.ods.standard pullrequest.yml
.github/workflows/Lib edFi.security.dataaccess manual.yml
.github/workflows/Lib edFi.security.dataaccess pullrequest.yml
.github/workflows/Pkg EdFi.Ods.CodeGen.yml
.github/workflows/Pkg EdFi.Ods.Minimal.Template.PostgreSQL.yml
.github/workflows/Pkg EdFi.Ods.Minimal.Template.TPDM.PostgreSQL.yml
.github/workflows/Pkg EdFi.Ods.Minimal.Template.TPDM.yml
.github/workflows/Pkg EdFi.Ods.Minimal.Template.yml
.github/workflows/Pkg EdFi.Ods.Populated.Template.PostgreSQL.yml
.github/workflows/Pkg EdFi.Ods.Populated.Template.TPDM.PostgreSQL.yml
.github/workflows/Pkg EdFi.Ods.Populated.Template.TPDM.yml
.github/workflows/Pkg EdFi.Ods.Populated.Template.yml
build.githubactions.ps1

Added function Get-IsWindows in build.githubactions.ps1 to remove ODS Implementation reference for InstallCredentialHandler  method and also remove ODS Implementation checkout from below workflows
1. Lib edFi.admin.dataaccess manual.yml 
2. Lib edFi.common manual.yml
3. Lib edFi.loadtools manual.yml
4. Lib edFi.ods.api manual.yml
5. Lib edFi.ods.common manual.yml
6. Lib edFi.loadtools manual.yml
7. Lib edFi.ods.api manual.yml
8. Lib edFi.ods.common manual.yml
9. Lib edFi.security.dataaccess manual.yml
Above workflows of manual & similar Pull request build and test all workflows uses only ODS repo ,so cache key created based on all nuget package exists all cs projects in ODS repo
Known fact that all 8 Database Templates  needs ODS Implementation repo which executes …

[ODS-5741] Nuget package caching enabled in Github Actions builds of Ed-Fi-ODS repo

---

.github/CODEOWNERS

This change makes it so that changes to the GitHub Actions yml files and to the main build script must be reviewed by a member of the new team, @Ed-Fi-Alliance-OSS/ods-platform-automation-owners. At this time, members are @semalaiappan @vimayya and @stephenfuqua.
This is the first change as we institute a policy of having tighter review on automation, as recommended by our security consultants.

[ODS-5772] Code owners file for Ed-Fi-ODS

---

.github/workflows/Pkg EdFi.Ods.Minimal.Template.PostgreSQL.yml
.github/workflows/Pkg EdFi.Ods.Minimal.Template.yml
.github/workflows/Pkg EdFi.Ods.Populated.Template.PostgreSQL.yml
.github/workflows/Pkg EdFi.Ods.Populated.Template.yml
Application/EdFi.Ods.Standard/version.utils.ps1
build.githubactions.ps1

Created ODS-5766 branch in Ed-Fi-Extensions to have CodeGen build passing
Application/EdFi.Ods.Standard/version.utils.ps1 will be totally removed in https://tracker.ed-fi.org/browse/ODS-5767

[ODS-5766] Add the Standard version to the minimal and populated templates

---

.github/workflows/Cleanup Caches by a branch.yml
.github/workflows/Lib edFi.admin.dataaccess manual.yml
.github/workflows/Lib edFi.common manual.yml
.github/workflows/Lib edFi.loadtools manual.yml
.github/workflows/Lib edFi.ods.api manual.yml
.github/workflows/Lib edFi.ods.common manual.yml
.github/workflows/Lib edFi.ods.standard manual.yml
.github/workflows/Lib edFi.security.dataaccess manual.yml
.github/workflows/Pkg EdFi.Database.Admin.yml
.github/workflows/Pkg EdFi.Database.Security.yml
.github/workflows/Pkg EdFi.Ods.CodeGen.yml
.github/workflows/Pkg EdFi.Ods.Minimal.Template.PostgreSQL.yml
.github/workflows/Pkg EdFi.Ods.Minimal.Template.TPDM.PostgreSQL.yml
.github/workflows/Pkg EdFi.Ods.Minimal.Template.TPDM.yml
.github/workflows/Pkg EdFi.Ods.Minimal.Template.yml
.github/workflows/Pkg EdFi.Ods.Populated.Template.PostgreSQL.yml
.github/workflows/Pkg EdFi.Ods.Populated.Template.TPDM.PostgreSQL.yml
.github/workflows/Pkg EdFi.Ods.Populated.Template.TPDM.yml
.github/workflows/Pkg EdFi.Ods.Populated.Template.yml
.github/workflows/Trgr InitDev workflows in Implementation repo.yml

Forked repositories need the ability to run actions without necessarily uploading artifacts to Azure or using GitHub secrets. This PR causes those actions to still fail in the Ed-Fi-Alliance-OSS repository if the secrets are missing, but pass in other repositories, skipping the steps that use the tokens.

[ODS-5775] Allow GitHub actions to run in forked repositories without secrets

---

Application/EdFi.Ods.Api/Startup/OdsStartupBase.cs
Application/EdFi.Ods.Features/Profiles/ProfileContentTypeContextMiddleware.cs

Include any profiles header (content-type header starting with "application/vnd.ed-fi." ) sent by an API client in the RequestResponseDetails log messages. The field is left blank in the log message if the client does not provide a profiles header in the request.
Example of log message including a profiles header:
`2023-04-19 19:19:16,898 [64] INFO  ClientId:43 RequestUrl:http://localhost:8765/data/v3/ed-fi/schools RequestMethod:POST ProfilesHeader:application/vnd.ed-fi.school.Test-Profile-Resource-WriteOnly.writable+json ResponseCode:403 ResponseMessage:Forbidden`

[ODS-5794] Enhance Request-Response logging with profile header information

---

Application/EdFi.Ods.Api/Container/Modules/ApplicationModule.cs
Application/EdFi.Ods.Api/Middleware/RequestResponseDetailsLoggerMiddleware.cs
Application/EdFi.Ods.Common/Configuration/ApiSettings.cs

- Take the steps necessary to create a new ODS instance. Then, add a request/response logging table to the ODS database by running one of the following create table scripts (the one matching the database engine in use):
_For an MS SQL database:_
```
IF (EXISTS (SELECT 1 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'dbo' 
AND  TABLE_NAME = 'RequestResponseContentLog'))
BEGIN
DROP TABLE [dbo].[RequestResponseContentLog];
END
CREATE TABLE [dbo].[RequestResponseContentLog] (
[Id] [int] IDENTITY (1, 1) NOT NULL,
[Date] [datetime] NOT NULL,
[Thread] [varchar] (255) NOT NULL,
[ApiClientId] [varchar] (255) NULL,
[Level] [varchar] (50) NULL,
[RequestUrl] [varchar] (255) NULL,
[RequestMethod] [varchar] (10) NULL,
[ProfilesHeader] [varchar] (255) NULL,
[RequestBody] [nvarchar] (max) NULL, …
```

[ODS-5329] Track the details of failed API calls

---

Application/EdFi.Ods.Api/Container/Modules/ApplicationModule.cs

With Profiles disabled, the registration of the "disabled feature" implementation with Autofac incorrectly using interface interceptors, which results in Autofac requiring interceptor registration (which is only registered by the Profiles module, which isn't run when feature is disabled).

[ODS-5791] Fix Postman integration test harness

---

Application/EdFi.Ods.Sandbox/Provisioners/SqlServerSandboxProvisioner.cs

Problem is existing code is  taking logical name for first row and using it for 2nd row just appending with _log .  then it comes EdFi_Ods_Minimal_Template_Data_Log which is not available in this case .  Code fix which takes 2nd row value for Log Data File
Steps to Reproduce 
1.  Run InitDev with YearSpecific 
2.  Create .bacpac file from EdFi_Ods_2024 database  with EdFi_Ods_Minimal_Template Name - Use Task Export Data -tier Application option
3.  Create .bacpac file from EdFi_Ods_2024 database  with EdFi_Ods_Populate_Template Name - Use Task Export Data -tier Application option
4. Run InitDev with Sandbox Mode
5.  Use Databases -> Import Data Tier Application to restore both  .bacpac file  
6.  Finally Run your Sandbox Admin from your local to see the error ERROR …

[ODS-5799] CodeFix for Logical Name issue with Log Type Data File

---

Application/EdFi.Ods.Api/Startup/OdsStartupBase.cs

The immediate cause of the 500 error was the `IdentitiesController` trying to use the "IdentityManagement" authorization policy, which did not exist if the Identity Management feature was disabled. This change resolves the 500 error when the Identity Management feature is turned off by adding an "IdentityManagement" authorization policy that always causes an unauthorized result in that situation. The expected behavior is for requests to the identities endpoints to return a 401 unauthorized response if the Identity Management feature is disabled rather than a 500 error with a stack trace.

[ODS-5933] Multitenancy Identities endpoint returns full stack message when feature is disabled

---

Application/EdFi.Ods.Tests/EdFi.Ods.Common/Specifications/EducationStandardSpecificationTests.cs

This updates `EducationStandardSpecificationTests` to use dummy classes rather than depending on code-generated classes. This prevents issues from arising when the data standard in use does not contain all of the classes needed to fully test `EducationStandardSpecification`.

[ODS-5910] Moving EducationStandardSpecificationTests to Unit Tests

---

Application/EdFi.Ods.Tests/EdFi.Ods.Features/OpenApiMetadata/Factories/OpenApiMetadataDefinitionsFactoryTests.cs
Application/Test.Common/AssertHelper.cs

This updates two unit tests to align with changes elsewhere in the solution and function as initially intended.

[ODS-5743] Unit test is incorrectly passing in OpenApiMetadataDefinitionsFactoryTests 

---

Postman Test Suite/Ed-Fi ODS-API Integration Test Suite.postman_collection.json
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/4.0.0/DataStandard_400_ApprovalTests.Verify.Extensions.Sample.1.0.0_Std_4.0.0_Models_Mappers_EntityMapper.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/4.0.0/DataStandard_400_ApprovalTests.Verify.Extensions.TPDM.1.1.0_Std_4.0.0_Models_Mappers_EntityMapper.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/4.0.0/DataStandard_400_ApprovalTests.Verify.Standard_Std_4.0.0_Models_Mappers_EntityMapper.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/5.0.0/DataStandard_500_ApprovalTests.Verify.Extensions.Sample.1.0.0_Std_5.0.0_Models_Mappers_EntityMapper.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/5.0.0/DataStandard_500_ApprovalTests.Verify.Extensions.TPDM.1.1.0_Std_5.0.0_Models_Mappers_EntityMapper.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/5.0.0/DataStandard_500_ApprovalTests.Verify.Standard_Std_5.0.0_Models_Mappers_EntityMapper.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Generators/EntityMapper.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Mustache/EntityMapper.mustache

ℹ️ **NOTE:** Though the changes to the Postman tests look huge, the actual addition to the Postman tests is found in this [commit](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/pull/839/commits/1d9ce388a9c1054405e6b64ab475bc1915dcb19f). The bulk of the diff seen was simply from a slight reorganization of the Offset/Limit/Total Count tests, and a correction of a spelling error.

[ODS-6039] Descriptors in key not compared using case-insensitive comparison in PUT requests

---

Application/EdFi.Ods.Features/OpenApiMetadata/Providers/OpenApiV3UpconversionProvider.cs
Utilities/DataLoading/EdFi.LoadTools/ApiClient/SwaggerMetadataRetriever.cs

This adds a step that updates the content-types for responses in the upconverted OpenApi V3.0 metadata to accurately reflect the content type returned from the server for each HTTP response code.

[ODS-6098] Read profile content-type is wrong in swagger 

---

Utilities/DataLoading/EdFi.BulkLoadClient.Console/EdFi.BulkLoadClient.Console.csproj
Utilities/DataLoading/EdFi.LoadTools.Test/EdFi.LoadTools.Test.csproj
Utilities/DataLoading/EdFi.LoadTools/EdFi.LoadTools.csproj
Utilities/DataLoading/EdFi.SmokeTest.Console/EdFi.SmokeTest.Console.csproj
Utilities/DataLoading/EdFi.XmlLookup.Console/EdFi.XmlLookup.Console.csproj

Some of the tests in this project require that the ODS/API is actively running. The application does not run from the `main-6x` branch yet since we are still in the middle of the upgrades. However, I was able to test from the `v6.1-patch2` branch. Thus I ran the ODS/API from the older branch, while running the `EdFi.LoadTools.Test` project from my feature branch for `main-6x`. Here you can see that all tests are passing:

[ODS-6170] Upgrade LoadTools to .NET 8

---

Utilities/VisualStudioProjectTemplates/EdFi.ProjectTemplates.Composites/Template_Project.csproj
Utilities/VisualStudioProjectTemplates/EdFi.ProjectTemplates.Extensions/EdFi.Ods.Extensions.ExtensionName.nuspec
Utilities/VisualStudioProjectTemplates/EdFi.ProjectTemplates.Extensions/Template_Project.csproj
Utilities/VisualStudioProjectTemplates/EdFi.ProjectTemplates.Profiles/Template_Project.csproj

I've tested that:
- A Composite/Profile/Extension project gets generated using net8 and works when added to the API.
- Calling nuget pack on the Extension's .nuspec works as expected.
- The .vsix gets installed and uninstalled successfully.

[ODS-6154] Migrate VisualStudioProjectTemplates to .NET 8

---

Application/EdFi.Ods.Api/Security/Authorization/EducationOrganizationIdNamesProvider.cs
Application/EdFi.Ods.Api/Security/Authorization/IEducationOrganizationIdNamesProvider.cs
Application/EdFi.Ods.Common/Specifications/PersonEntitySpecification.cs
Application/EdFi.Ods.Common/Specifications/UniqueIdSpecification.cs

Role-named fields in EdOrg Only and People Only authorization strategies do not apply appropriate filters

[ODS-6266] Cherry Picked from ODS-6045 Role-named fields in EdOrg Only and People Only authorization strategies do not apply appropriate filters

---

Application/EdFi.Ods.Common/Models/Domain/DomainModelConventionExtensions.cs
Application/EdFi.Ods.Common/Specifications/UniqueIdConventions.cs
Application/EdFi.Ods.Standard/Container/Modules/RelationshipsAuthorizationContextDataProviderModule.cs
Application/EdFi.Ods.Standard/Container/Modules/RelationshipsAuthorizationContextDataProviderOverridesModule.cs
Application/EdFi.Ods.Standard/Security/Authorization/Overrides/StudentAssessmentRelationshipsAuthorizationContextDataProvider.cs

…ReportingSchool (#835)
* Override for auth by reported school on student assessment (#814)
In order to use role based field for establishing edorg relationship, a custom authorization context data provider implementation is needed to use ReportingSchoolId.  This  follows the pattern established in DisciplineActionRelationshipsAuthorizationContextDataProvider.
* Reduce debug noise and performance hit related to logging cache hits.
* Updated IsEducationOrganizationIdName method to allow for role-named EdOrgId-related identifiers.
* Updated IsPersonIdentifier method to allow for role-named person identifiers.
* Updated main data context provider registration module to register context data providers succinctly and to avoid registering any of the custom override providers.
* Minor cleanup of …

[ODS-6265] Cherry-Pick ODS-5987 into main6x - Relationship Authorization for StudentAssessment based on ReportingSchool

---

Utilities/DataLoading/EdFi.BulkLoadClient.Console/EdFi.BulkLoadClient.Console.csproj
Utilities/DataLoading/EdFi.BulkLoadClient.Console/Program.cs
Utilities/DataLoading/EdFi.SmokeTest.Console/EdFi.SmokeTest.Console.csproj
Utilities/DataLoading/EdFi.SmokeTest.Console/Program.cs

Steps to test:
- Open **LoadTools.sln** in VS2022
- Right-click on either the **EdFi.BulkLoadClient.Console** or **EdFi.SmokeTest.Console** project
- Click "**Manage User Secrets**" in the context menu - this should open an empty **secrets.json** file
- Save an API key and secret in the **secrets.json** file using the following format
```
{
"OdsApi:Key": "your key",
"OdsApi:Secret": "your secret"
}
```
- Run the console application and observe that the key and secret saved in **secrets.json** are used, overriding any values provided in **appsettings.json** or as command line arguments

[ODS-4830] Add Secret Support to the Load Tools

---

Utilities/DataLoading/EdFi.LoadTools.Test/EdFi.LoadTools.Test.csproj
Utilities/DataLoading/EdFi.LoadTools.Test/SmokeTests/APIGetTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/SmokeTests/GetDependenciesTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/SmokeTests/GetVersionTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/SmokeTests/ModelDependencySortTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/SmokeTests/PropertyBuilderTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/XsdFileRetrieverTests.cs

This transitions the LoadTools tests from Moq to FakeItEasy. The changes include updating package references, replacing `Mock.Of` with `A.Fake`, and utilizing `A.CallTo().Returns()` for property setups. Additionally, there's a change in `XsdFileRetrieverTests`, which updates the expected data standard to "**5.0.0**" and adds the "**TPDM**" extension, which is required for the manual test `Should_get_xsd_metadata_information_and_download_files` to pass when running against the latest initdev ODS deployment.

[ODS-3746] Update EdFi.LoadTools.Test to use FakeItEasy

---

Application/EdFi.Ods.Api/Container/Modules/ApplicationModule.cs
Application/EdFi.Ods.Api/Filters/EnforceAssignedProfileUsageFilter.cs
Application/EdFi.Ods.Api/Serialization/ProfilesAwareContractResolver.cs
Application/EdFi.Ods.Api/Startup/NewtonsoftJsonOptionConfigurator.cs
Application/EdFi.Ods.Common/Models/IMappingContractProvider.cs
Application/EdFi.Ods.Common/Models/MappingContractProvider.cs
Application/EdFi.Ods.Features/Container/Modules/OpenApiMetadataModule.cs
Application/EdFi.Ods.Features/Container/Modules/ProfilesModule.cs
Application/EdFi.Ods.Features/Notifications/ProfilesExpireCacheHandler.cs
Application/EdFi.Ods.Features/OpenApiMetadata/Providers/OpenApiMetadataCacheProvider.cs
Application/EdFi.Ods.Features/Profiles/ProfileMetadataCacheExpiredNotificationHandler.cs

MediatR registers all handler implementations as Transient, so I grouped all profile-related cached data objects to have the cache cleared by the same handler.

[ODS-6349] Profiles expiration doesn't clear mapping contracts

---

Application/EdFi.Ods.Standard/Standard/4.0.0/Artifacts/MsSql/Data/Security/2145-Add-RelationshipsWithStudentsOnlyThroughResponsibilityIncludingDeletes-strategy.sql
Application/EdFi.Ods.Standard/Standard/4.0.0/Artifacts/PgSql/Data/Security/2145-Add-RelationshipsWithStudentsOnlyThroughResponsibilityIncludingDeletes-strategy.sql
Application/EdFi.Ods.Standard/Standard/5.1.0/Artifacts/MsSql/Data/Security/2145-Add-RelationshipsWithStudentsOnlyThroughResponsibilityIncludingDeletes-strategy.sql
Application/EdFi.Ods.Standard/Standard/5.1.0/Artifacts/PgSql/Data/Security/2145-Add-RelationshipsWithStudentsOnlyThroughResponsibilityIncludingDeletes-strategy.sql

Upgrading the Security DB:
From EdFi.Suite3.RestApi.Databases.Standard.5.0.0.7.1.1192
To EdFi.Suite3.RestApi.Databases.Standard.5.1.0.7.2.1186
https://dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.Suite3.RestApi.Databases.Standard.5.1.0/versions/7.2.1186
SELECT *   FROM [EdFi_Security].[dbo].[DeployJournal]  where ScriptName like '%RelationshipsWithStudentsOnlyThroughResponsibilityIncludingDeletes-strategy%'
SELECT *  FROM [EdFi_Security].[dbo].[AuthorizationStrategies] 
where AuthorizationStrategyName ='RelationshipsWithStudentsOnlyThroughResponsibilityIncludingDeletes'

[ODS-6394] Added If  Check Condition for RelationshipsWithStudentsOnlyThroughResponsibilityIncludingDeletes

---

.github/workflows/Lib edFi.common.yml
Application/EdFi.Admin.DataAccess/EdFi.Admin.DataAccess.csproj
Application/EdFi.Common/Database/SqlConnectionStringBuilderAdapter.cs
Application/EdFi.Common/EdFi.Common.csproj
Application/EdFi.Common/Security/Pbkdf2HmacSha1SecureHasher.cs
Application/EdFi.Ods.Api/EdFi.Ods.Api.csproj
Application/EdFi.Ods.Common/EdFi.Ods.Common.csproj
Application/EdFi.Ods.Repositories.NHibernate.Tests/EdFi.Ods.Repositories.NHibernate.Tests.csproj
Application/EdFi.Ods.Sandbox/EdFi.Ods.Sandbox.csproj
Application/EdFi.Ods.Tests/EdFi.Ods.Tests.csproj
Application/EdFi.Security.DataAccess/EdFi.Security.DataAccess.csproj
Application/EdFi.TestObjects/EdFi.TestObjects.csproj
Utilities/DataLoading/EdFi.BulkLoadClient.Console/EdFi.BulkLoadClient.Console.csproj
Utilities/DataLoading/EdFi.LoadTools.Test/EdFi.LoadTools.Test.csproj
Utilities/DataLoading/EdFi.LoadTools/EdFi.LoadTools.csproj
Utilities/DataLoading/EdFi.SmokeTest.Console/EdFi.SmokeTest.Console.csproj
Utilities/DataLoading/EdFi.XmlLookup.Console/EdFi.XmlLookup.Console.csproj
tests/EdFi.Admin.DataAccess.UnitTests/EdFi.Admin.DataAccess.UnitTests.csproj
tests/EdFi.Common.UnitTests/EdFi.Common.UnitTests.csproj
tests/EdFi.Common.UnitTests/Inflection/InflectorTests.cs
tests/EdFi.Ods.WebApi.CompositeSpecFlowTests/EdFi.Ods.WebApi.CompositeSpecFlowTests.csproj
tests/EdFi.Ods.WebApi.IntegrationTests/EdFi.Ods.WebApi.IntegrationTests.csproj
tests/EdFi.Security.DataAccess.UnitTests/EdFi.Security.DataAccess.UnitTests.csproj
tests/EdFi.TestFixture/EdFi.TestFixture.csproj

Changes included in this PR:
- Update the `EdFi.Common` solution to net8.
- Re-generate the package (`EdFi.Suite3.Common`).
- Reference the newly generated package.
The builds will fail until the rest of the projects get migrated to net8, which will be done in subsequent stories.

[ODS-6229] Migrate EdFi.Common to .NET 8

---

Utilities/DataLoading/EdFi.BulkLoadClient.Console/EdFi.BulkLoadClient.Console.csproj
Utilities/DataLoading/EdFi.LoadTools.Test/EdFi.LoadTools.Test.csproj
Utilities/DataLoading/EdFi.LoadTools.Test/EducationOrganizationCacheLookupStepTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/ExtensionMethodsTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/LookupPipelineTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/MapXmlLookupToGetByExampleJsonStepTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/Mapping/MapperTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/OAuthTokenHandlerTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/PercentMatchToTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/PropertyMapperTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/ResourceReferencePreloadStepTest.cs
Utilities/DataLoading/EdFi.LoadTools.Test/SmokeTests/APIGetTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/SmokeTests/GetDependenciesTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/SmokeTests/GetVersionTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/SmokeTests/ModelDependencySortTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/SmokeTests/PropertyBuilderTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/SwaggerRetrieverTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/UtilitiesTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/XmlLookupPipeline/XmlToWorkItemsProcessorTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/XmlLookupToResourceProcessorTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/XmlReferenceCacheTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/XmlResourceHashCacheTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/XmlResourcePipelineTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/XsdMetadataRetrievalTests.cs
Utilities/DataLoading/EdFi.LoadTools/EdFi.LoadTools.csproj
Utilities/DataLoading/EdFi.SmokeTest.Console/EdFi.SmokeTest.Console.csproj
Utilities/DataLoading/EdFi.XmlLookup.Console/EdFi.XmlLookup.Console.csproj

Some of the tests in this project require that the ODS/API is actively running. The application does not run from the main-5x branch yet since we are still in the middle of the upgrades. However, I was able to test from the v5.3-patch5 tag. Thus I ran the ODS/API from the older tag, while running the EdFi.LoadTools.Test project from my feature branch for main-5x. Here you can see that all tests are passing:

[ODS-6226] Migrate DataLoading solution to .NET 8

---

Utilities/DataLoading/EdFi.LoadTools/SmokeTest/PropertyBuilders/DescriptorPropertyBuilder.cs
Utilities/DataLoading/EdFi.LoadTools/SmokeTest/PropertyBuilders/NamespacePropertyBuilder.cs
Utilities/SdkGen/EdFi.SdkGen.Console/EdFi.OdsApi.Sdk.nuspec
Utilities/SdkGen/EdFi.SdkGen.Console/EdFi.SdkGen.Console.csproj
Utilities/SdkGen/EdFi.SdkGen.Console/OpenApiCodeGenCliRunner.cs
Utilities/SdkGen/EdFi.SdkGen.Console/Options.cs

Summary of Changes:
- Update SdkGen project to use .NET 8
- Add JavaPath parameter to SdkGen cli
- Update Java CodeGen utility default version selection to 7.2.0
- Update SmokeTest to handle Var prefixes (added by the new version of Java CodeGen utility) on reserved words

[ODS-6227] Migrate SdkGen to target .NET 8 (5.x)

---

.github/workflows/CodeQL Security Scan.yml
.github/workflows/Pkg EdFi.ProjectTemplates.Installer.yml
Application/Directory.Build.props
Application/EdFi.Ods.Standard/Artifacts/MsSql/Structure/Ods/1330-UpdateVersionTo54.sql
Application/EdFi.Ods.Standard/Artifacts/PgSql/Structure/Ods/1330-UpdateVersionTo54.sql
Utilities/DataLoading/EdFi.LoadTools.Test/EdFi.LoadTools.Test.csproj
Utilities/DataLoading/EdFi.LoadTools.Test/Mapping/MapperTests.cs
Utilities/DataLoading/EdFi.LoadTools/EdFi.LoadTools.csproj
Utilities/DataLoading/EdFi.LoadTools/Engine/ExtensionMethods.cs
Utilities/DataLoading/EdFi.LoadTools/SmokeTest/SdkTests/BaseTest.cs
Utilities/DataLoading/EdFi.LoadTools/SmokeTest/SdkTests/DeleteTest.cs
Utilities/DataLoading/EdFi.LoadTools/SmokeTest/SdkTests/GetByIdTest.cs
Utilities/DataLoading/EdFi.LoadTools/SmokeTest/SdkTests/PostTest.cs
Utilities/DataLoading/EdFi.LoadTools/SmokeTest/SdkTests/PutTest.cs
Utilities/SdkGen/EdFi.SdkGen.Console/EdFi.OdsApi.Sdk.nuspec

Changes included in this PR:
- Brought a subset of changes from #1100
- Updated the DB Function `util.GetEdFiOdsVersion` to return '5.4'
- Updated references to `EdFi.Suite3.OdsApi.TestSdk` to the latest version
- General fixes to the SDK Smoke tests
Note that the builds `Pkg EdFi.Database.Admin` and `Pkg EdFi.Database.Security` failed, but this PR didn't change any of those DBs (these builds have always failed in the `main-5x` branch), so we might consider fixing these builds in a different PR.

[ODS-6290][ODS-6436][ODS-6227] Pre release tasks for ODS/API 5.4

---

Application/EdFi.Ods.Api/Caching/InstanceSecurityRepositoryCache.cs

- Removes the `StringComparison` parameter from the LINQ expression used to find the Ed-Fi ODS API application entry in the security database.

[ODS-6442] Authentication problem when using instance year-specific mode (5.x)

---

Application/EdFi.Ods.Api/Container/Modules/ApplicationModule.cs
Application/EdFi.Ods.Api/Security/Authentication/EdFiAdminAccessTokenFactory.cs
Application/EdFi.Ods.Common/Configuration/ApiSettings.cs
Application/EdFi.Ods.Common/Exceptions/TooManyTokensException.cs
Artifacts/MsSql/Structure/Admin/0175-Add-CreateClientAccessToken.sql
Artifacts/PgSql/Structure/Admin/0175-Add-CreateClientAccessToken.sql

- Added a configuration setting to limit the number of valid bearer tokens issued per client
- Added a new custom exception for handling instances where clients attempt to exceed the token limit
- Added stored procedures in SQL and PostgreSQL to manage client access token creation and enforce the token limit

[ODS-6418] Enforce token limits on API clients

---

Application/EdFi.Ods.Features/ChangeQueries/ChangeVersionFilterMappingNHibernateConfigurationActivity.cs

Stop NHibernate from retrieving the ChangeVersion after every INSERT and UPDATE statement for the aggregate root entities.

[ODS-6482] Eliminate unnecessary database roundtrip for ChangeVersion after all upserts

---

Application/EdFi.Ods.Api/Startup/OdsStartupBase.cs

Update EdFi.Ods.WebApi  project Appsettings as  :"StartUpClassName": "CustomStartup"
Add below CustomStartup  class for testing this change 
using Autofac;
using EdFi.Ods.Api.Startup;
using EdFi.Ods.Common.Configuration;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
namespace EdFi.Ods.WebApi
{
public class CustomStartup : OdsStartupBase
{
public CustomStartup(IWebHostEnvironment env, IConfiguration configuration) : base(env, configuration)
{
}
public override void ConfigureServices(IServiceCollection services)
{
base.ConfigureServices(services);
}
public override void ConfigureContainer(ContainerBuilder builder)
{ …

[ODS-5622] Make the ODSStartup configurable

---

Application/EdFi.Ods.Standard/Standard/4.0.0/Artifacts/MsSql/Structure/Ods/Changes/0230-CreateIndirectUpdateCascadeTriggers.sql
Application/EdFi.Ods.Standard/Standard/4.0.0/Artifacts/PgSql/Structure/Ods/Changes/0230-CreateIndirectUpdateCascadeTriggers.sql
Application/EdFi.Ods.Standard/Standard/5.2.0/Artifacts/MsSql/Structure/Ods/Changes/0230-CreateIndirectUpdateCascadeTriggers.sql
Application/EdFi.Ods.Standard/Standard/5.2.0/Artifacts/PgSql/Structure/Ods/Changes/0230-CreateIndirectUpdateCascadeTriggers.sql

Application/EdFi.Ods.Standard/Standard/4.0.0/Artifacts/MsSql/Structure/Ods/Changes/0230-CreateIndirectUpdateCascadeTriggers.sql is not coming from MetaEd Artifacts

[ODS-6638] Updated Scripts to use CREATE OR ALTER TRIGGER instead of CREATE TRIGGER

---

Application/EdFi.Ods.Common/Models/Resource/Resource.cs
Application/EdFi.Ods.Common/Models/Resource/ResourceClassBase.cs

Semantic Model Enhancement: Prevent LinkedCollections to like-named resources from resulting in an exception while building the LinkedCollectionByName dictionary.

[ODS-6684] ProblemDetails response construction fails under edge-case extension scenario
