Ed-Fi-Alliance-OSS/Ed-Fi-ODS

Postman Test Suite/Ed-Fi ODS-API Integration Test Suite.postman_collection.json

Added below 5 Use case for this postman scripting
Scenario 1 - Create Person With new unqiue  sourceSystemDescriptor and associate with Staff
Scenario 2 - Create same Person With 2 different new unqiue sourceSystemDescriptor and associate with Staff
Scenario 3 - Create Person With  new unqiue sourceSystemDescriptor and associate with Student
Scenario 4 - Create Person With  new unqiue sourceSystemDescriptor and associate the same person with multiple Student
Scenario 5 - Create Person With new unqiue sourceSystemDescriptor and Associate with Parent

[ODS-4214] Create postman tests for Person Entity

---

Application/EdFi.Ods.Api/Extensibility/ExtensionNHibernateConfigurationProvider.cs

[ODS-4207] Unable to Retrieve Data From Subclasses of Education Organization

---

Utilities/DataLoading/EdFi.BulkLoadClient.Console/App.config
Utilities/DataLoading/EdFi.LoadTools.Test/XmlReferenceCacheTests.cs
Utilities/DataLoading/EdFi.LoadTools.Test/XmlResourcePipelineTests.cs
Utilities/DataLoading/EdFi.LoadTools/ApiLoaderApplication.cs
Utilities/DataLoading/EdFi.LoadTools/Engine/ApiLoaderWorkItem.cs
Utilities/DataLoading/EdFi.LoadTools/Engine/InterchangePipeline/InterchangePipeline.cs
Utilities/DataLoading/EdFi.LoadTools/Engine/Interfaces.cs
Utilities/DataLoading/EdFi.LoadTools/Engine/ResourcePipeline/SubmitResource.cs
Utilities/DataLoading/EdFi.LoadTools/LogContext.cs

Generally lowering the amount of default logging output, reduced down to Debug in most cases.  Cleaned up what renders in console to make it easier to view.

[ODS-4227] Adjustments to logging and retry queue

---

Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval Tests/GeneratedFileApprovalTests.Verify_All.ForScenario.Extensions.Sample_Models_Entities_Entities.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval Tests/GeneratedFileApprovalTests.Verify_All.ForScenario.Extensions.TPDM_Models_Entities_Entities.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Mustache/Entities_PropertyAccessors.mustache

[ODS-3164] 3.1 DisciplineIncident: cannot change staffReference

---

Application/EdFi.Ods.Api.Startup/Features/Installers/SecurityInstaller.cs
Application/EdFi.Ods.Common/Security/EdFiOdsApiClaimTypes.cs
Application/EdFi.Ods.Security/Authorization/EdFiAuthorizationProvider.cs
Application/EdFi.Ods.Security/Authorization/ResourceClaimUriProvider.cs
Application/EdFi.Ods.Security/Claims/ClaimsIdentityProvider.cs

Paired with https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/pull/47

[ODS-4321] Update Authorization Strategies for TPDM Aggregates

---

Application/EdFi.Ods.Api/Controllers/TokenController.cs
Application/EdFi.Ods.Tests/EdFi.Ods.Api/Controllers/ControllerHelper.cs
Application/EdFi.Ods.Tests/EdFi.Ods.Api/Controllers/TokenControllerTests.cs
Application/EdFi.Ods.Tests/EdFi.Ods.Api/Controllers/TokenControllerUsingJsonTests.cs

…sts in TokenControllerUsingJsonTests

[ODS-4430] Add support for mix OAuth support to the net core branch

---

Application/EdFi.Ods.Api/NHibernate/Architecture/EdFiNpgsqlDriver.cs
Application/EdFi.Ods.Common/Infrastructure/PostgreSql/EdFiNpgsqlDriver.cs
Application/EdFi.Ods.Common/Infrastructure/PostgreSql/PostgreSqlDatabaseEngineNHibernateConfigurationActivity.cs
Application/EdFi.Ods.Common/Infrastructure/SqlServer/EdFiSql2008ClientDriver.cs
Application/EdFi.Ods.Common/Models/Domain/PropertyTypeExtensions.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval Tests/GeneratedFileApprovalTests.Verify_All.ForScenario.Extensions.Sample_EntityOrmMappings_MsSql_EntityOrmMappings.generated.hbm.approved.xml
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval Tests/GeneratedFileApprovalTests.Verify_All.ForScenario.Extensions.Sample_EntityOrmMappings_PgSql_EntityOrmMappings.generated.hbm.approved.xml
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval Tests/GeneratedFileApprovalTests.Verify_All.ForScenario.Extensions.TPDM_EntityOrmMappings_MsSql_EntityOrmMappings.generated.hbm.approved.xml
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval Tests/GeneratedFileApprovalTests.Verify_All.ForScenario.Extensions.TPDM_EntityOrmMappings_PgSql_EntityOrmMappings.generated.hbm.approved.xml
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Database/DatabaseSchema/IDatabaseTypeTranslator.cs

See also https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/pull/118.

[ODS-4537] Support PostgreSQL "money" data type in API GetByExample requests

---

Application/EdFi.Ods.Api/Container/Modules/ExtensionsModule.cs

Adding code to ExtensionsModule to ensure the generated extension IRelationshipsAuthorizationContextDataProvider implementations are registered.

[ODS-4586] SmokeTest getting for 500 InternalServerError TPDM

---

Application/EdFi.Security.DataAccess/Contexts/PostgresSecurityContext.cs
Application/EdFi.Security.DataAccess/Contexts/SecurityContextFactory.cs
Application/EdFi.Security.DataAccess/EdFi.Security.DataAccess.csproj
Application/EdFi.Security.DataAccess/Providers/SecurityDatabaseConnectionStringProvider.cs
Application/EdFi.Security.DataAccess/Repositories/CachedSecurityRepository.cs
Application/EdFi.Security.DataAccess/Repositories/SecurityRepository.cs
Application/EdFi.Security.DataAccess/Utils/ValidateDatabase.cs
tests/EdFi.Security.DataAccess.UnitTests/Contexts/SecurityContextFactoryTests.cs
tests/EdFi.Security.DataAccess.UnitTests/Repositories/CachedSecurityRepositoryTests.cs

Removing unused EdFi.Ods.Common reference and using statements that referenced it.

[ODS-4577] Investigate Shared library dependency on EdFi.Ods.Common

---

CONTRIBUTORS.md

Adding contributors for ODS-4332 (InstanceYear API support)

Adding contributors for ODS-4332

---

Postman Test Suite/Ed-Fi ODS-API Integration Test Suite ResponseTests.postman_collection.json

(This also fixes the broken limit-related tests in the build.)

[ODS-4656] Add Postman test coverage for the new limit=0 parameter value support

---

Application/EdFi.Ods.Common/Models/Definitions/AssociationDefinition.cs
Application/EdFi.Ods.Common/Models/Domain/Association.cs
Application/EdFi.Ods.Common/Models/Domain/AssociationView.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Generators/Entities.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Mustache/Entities.mustache

* note this is backwards compatible

[ODS-4612] Optional References in ODS /API as directed by ed-fi model

---

Utilities/CodeGeneration/EdFi.Ods.CodeGen/Mustache/Entities.mustache

See also https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/pull/270

[ODS-4922] CalendarDates Endpoint with LearningModality

---

Utilities/DataLoading/EdFi.LoadTools/BulkLoadClient/Application/BulkLoadClientConfiguration.cs
Utilities/DataLoading/EdFi.LoadTools/BulkLoadClient/LoadProcess.cs

[ODS-4989] Bulk Load Client is not working 2022 Year Instance

---

Artifacts/MsSql/Structure/Admin/0080-Add-Index-ClientAccessTokens-Expiration.sql
Artifacts/PgSql/Structure/Admin/0080-Add-Index-ClientAccessTokens-Expiration.sql

Manually tested in PostgreSql and SQL Server

[ODS-5030] Deleting Expired Tokens is resulting in sql wait timeouts under heavy load

---

Application/EdFi.Admin.DataAccess/EdFi.Admin.DataAccess.csproj
Application/EdFi.Ods.Api/EdFi.Ods.Api.csproj
Application/EdFi.Ods.Common/EdFi.Ods.Common.csproj
Application/EdFi.Ods.Repositories.NHibernate.Tests/EdFi.Ods.Repositories.NHibernate.Tests.csproj
Application/EdFi.Ods.Sandbox/EdFi.Ods.Sandbox.csproj
Application/EdFi.Ods.Tests/EdFi.Ods.Tests.csproj
Application/EdFi.Security.DataAccess/EdFi.Security.DataAccess.csproj
Application/EdFi.TestObjects/EdFi.TestObjects.csproj
Utilities/DataLoading/EdFi.BulkLoadClient.Console/EdFi.BulkLoadClient.Console.csproj
Utilities/DataLoading/EdFi.LoadTools.Test/EdFi.LoadTools.Test.csproj
Utilities/DataLoading/EdFi.LoadTools/EdFi.LoadTools.csproj
Utilities/DataLoading/EdFi.SmokeTest.Console/EdFi.SmokeTest.Console.csproj
Utilities/DataLoading/EdFi.XmlLookup.Console/EdFi.XmlLookup.Console.csproj
tests/EdFi.Admin.DataAccess.UnitTests/EdFi.Admin.DataAccess.UnitTests.csproj
tests/EdFi.Ods.WebApi.CompositeSpecFlowTests/EdFi.Ods.WebApi.CompositeSpecFlowTests.csproj
tests/EdFi.Ods.WebApi.IntegrationTests/EdFi.Ods.WebApi.IntegrationTests.csproj
tests/EdFi.Security.DataAccess.UnitTests/EdFi.Security.DataAccess.UnitTests.csproj

After this PR gets merged, I will regenerate the following packages:
- EdFi.Admin.DataAccess
- EdFi.LoadTools
- EdFi.Ods.Api
- EdFi.Ods.Common
- EdFi.Ods.Standard
- EdFi.Security.DataAccess

[ODS-5078] Update internal EdFi.Common package version

---

Application/EdFi.Ods.Api/Constants/ApiVersionConstants.cs
Application/EdFi.Ods.Api/EdFi.Ods.Api.csproj
Application/EdFi.Ods.Common/EdFi.Ods.Common.csproj
Application/EdFi.Ods.Repositories.NHibernate.Tests/EdFi.Ods.Repositories.NHibernate.Tests.csproj
Application/EdFi.Ods.Sandbox/EdFi.Ods.Sandbox.csproj
Application/EdFi.Ods.Tests/EdFi.Ods.Tests.csproj
Application/Test.Common/Test.Common.csproj
tests/EdFi.Admin.DataAccess.UnitTests/EdFi.Admin.DataAccess.UnitTests.csproj
tests/EdFi.Ods.WebApi.CompositeSpecFlowTests/EdFi.Ods.WebApi.CompositeSpecFlowTests.csproj
tests/EdFi.Ods.WebApi.IntegrationTests/EdFi.Ods.WebApi.IntegrationTests.csproj
tests/EdFi.Security.DataAccess.UnitTests/EdFi.Security.DataAccess.UnitTests.csproj

[ODS-5100] Use EdFi.Admin.DataAccess and EdFi.Security.DataAccess packages in ODS solution

---

Application/EdFi.Ods.Standard/Artifacts/MsSql/Structure/Ods/1303-AuthViewStudentUsiToEducationOrganizationId.sql
Application/EdFi.Ods.Standard/Artifacts/MsSql/Structure/Ods/1304-AuthViewParentUsiToEducationOrganizationId.sql
Application/EdFi.Ods.Standard/Artifacts/MsSql/Structure/Ods/1305-AuthViewsStaffUsiToEducationOrganizationId.sql
Application/EdFi.Ods.Standard/Artifacts/MsSql/Structure/Ods/1306-AuthViewStudentUsiToEducationOrganizationIdThroughEdOrgAssociation.sql
Application/EdFi.Ods.Standard/Artifacts/PgSql/Structure/Ods/1303-AuthViewStudentUsiToEducationOrganizationId.sql
Application/EdFi.Ods.Standard/Artifacts/PgSql/Structure/Ods/1304-AuthViewParentUsiToEducationOrganizationId.sql
Application/EdFi.Ods.Standard/Artifacts/PgSql/Structure/Ods/1305-AuthViewsStaffUsiToEducationOrganizationId.sql
Application/EdFi.Ods.Standard/Artifacts/PgSql/Structure/Ods/1306-AuthViewStudentUsiToEducationOrganizationIdThroughEdOrgAssociation.sql

Updated views to prevent duplicates in the results (and to be oriented around source-to-target join order).

[ODS-5090] Limit/Offset/Total Count incorrect with multiple enrollments

---

Utilities/GenerateSecurityGraphs/GenerateSecurityGraphs/Program.cs

See my comment in ODS-5179 for the root cause explanation.

[ODS-5179] Security visualization utility shows incorrect authorization strategy

---

Artifacts/MsSql/Structure/Security/0050-AddUniqueConstraintResourceClaimsClaimName.sql
Artifacts/PgSql/Structure/Security/0050-AddUniqueConstraintResourceClaimsClaimName.sql

I had to reduce the size of ClaimName to nvarchar(850) so that it would fit in the unique index.

[ODS-3415] Add unique constraints

---

Application/EdFi.Ods.Features/XsdMetadata/XsdMetadataController.cs
Samples/Extensions/StudentTranscript/StudentTranscriptMetaEd/MetaEdOutput/SampleStudentTranscript/Interchange/EXTENSION-Interchange-Descriptors-Extension.xsd
Samples/Extensions/StudentTranscript/StudentTranscriptMetaEd/MetaEdOutput/SampleStudentTranscript/Interchange/EXTENSION-Interchange-StudentTranscript-Extension.xsd
Samples/Extensions/StudentTranscript/StudentTranscriptMetaEd/MetaEdOutput/SampleStudentTranscript/XSD/EXTENSION-Ed-Fi-Extended-Core.xsd
Samples/Extensions/StudentTransportation/StudentTransportationMetaEd/MetaEdOutput/SampleStudentTransportation/Interchange/EXTENSION-Interchange-StudentTransportation-Extension.xsd
Samples/Extensions/StudentTransportation/StudentTransportationMetaEd/MetaEdOutput/SampleStudentTransportation/XSD/EXTENSION-Ed-Fi-Extended-Core.xsd
Utilities/DataLoading/EdFi.LoadTools/ApiClient/XsdMetadata/XsdFilesRetriever.cs

To Run the EdFi.BulkLoadClient.Console project 
you can run with 'sample-student-transcript' for --extension parameter  and also SampleStudentTranscript to test this change
{
"profiles": {
"EdFi.BulkLoadClient.Console": {
"commandName": "Project",
"commandLineArgs": "--baseUrl \"http://localhost:54746\" --data \"C:\\Ed-Fi-SampleDataLoad\\Sample XML1\" --extension \"SampleStudentTranscript\" --working \"C:\\Ed-Fi-SampleDataLoad\\Working1\" --key \"87XzD0a3i4oIh5jyVLb9u\" --secret \"OqGkhQztCpAjeWsKxbXLY\" --include-stats --retries 1 --maxRequests 1 --force --novalidation"
}
}
}
386  INFO  EdFi.LoadTools.OdsVersionInformation - Getting version information from 'http://localhost:54746
696  INFO  EdFi.LoadTools.ApiClient.XsdMetadata.XsdFilesRetriever - Removing existing xsd files from …

ODS-5307 Unable to bulk upload descriptors to extensions with compound names

---

Utilities/DataLoading/EdFi.LoadTools/SmokeTest/SdkTests/PostTest.cs

…t in a create to the created dictionary

[ODS-5315] Fix destructive Smoke Test error related to incorrect delete order

---

.github/workflows/edFi.ods.api manual.yml
.github/workflows/edFi.ods.common manual.yml
Application/EdFi.Ods.Api/EdFi.Ods.Api.csproj
Application/EdFi.Ods.Common/EdFi.Ods.Common.csproj
Application/EdFi.Ods.Standard/EdFi.Ods.Standard.csproj
build.ps1

after doing package reference in SK project and it test that it's working fine 
<PackageReference Include="EdFi.Suite3.Ods.Api" Version="6.0.26" />
<PackageReference Include="EdFi.Suite3.Ods.Common" Version="6.0.27" />
<PackageReference Include="EdFi.Suite3.Ods.Standard" Version="6.0.14" />

ODS-5572 EdFi.Suite3.Ods.Api & EdFi.Suite3.Ods.Standard nuget package is missing with package reference for dependencies

---

Application/EdFi.Ods.Api/Container/Modules/PersistenceModule.cs
Application/EdFi.Ods.Api/Container/Modules/SecurityRepositoryModule.cs

[ODS-5575] Cache settings initialization is broken

---

.github/workflows/Packages - EdFi.Ods.Minimal.Template.TPDM.PostgreSQL.yml

https://intedfitools1.msdf.org/buildConfiguration/EdFi_SharedResources_OdsPlatformChangeQuery_OdsApi_Packages_EdFiOdsMinimalTemplateTpdmPostgreSQL?branch=&buildTypeTab=overview&mode=builds#all-projects  you can refer this build to verfiy each step from teamcity

ODS-5562 Move EdFi.Ods.Minimal.Template.TPDM.PostgreSQL Package build to Github Actions

---

.github/workflows/Packages - EdFi.Ods.Minimal.Template.TPDM.PostgreSQL.yml
.github/workflows/Packages - EdFi.Ods.Populated.Template.TPDM.PostgreSQL.yml

triggered-from-tpdmartifacts-repo in the ODS repo will be triggered only after merge of this PR 
triggered-from-datastandard-repo in the ODS repo will be triggered only after merge of this PR

ODS-5564 Move EdFi.Ods.Populated.Template.TPDM.PostgreSQL Package build to Github Actions

---

Application/EdFi.Ods.Api/Caching/InstanceSecurityRepositoryCache.cs
Application/EdFi.Ods.Api/Constants/RouteConstants.cs
Application/EdFi.Ods.Api/Container/Modules/InstanceYearSpecificModule.cs
Application/EdFi.Ods.Api/Controllers/DataManagementControllerBase.cs
Application/EdFi.Ods.Api/Filters/DataManagementRequestContextFilter.cs
Application/EdFi.Ods.Api/Providers/EdFiOdsInstanceYearSpecificIdentificationProvider.cs
Application/EdFi.Ods.Tests/EdFi.Ods.Api/Caching/StubSecurityContext.cs
Utilities/DataLoading/EdFi.BulkLoadClient.Console/Application/CommandLineOverrides.cs
Utilities/DataLoading/EdFi.BulkLoadClient.Console/Properties/launchSettings.json
Utilities/DataLoading/EdFi.BulkLoadClient.Console/appsettings.json
Utilities/DataLoading/EdFi.LoadTools/BulkLoadClient/Application/BulkLoadClientConfiguration.cs
Utilities/DataLoading/EdFi.LoadTools/BulkLoadClient/Application/BulkLoadClientConfigurationValidator.cs
Utilities/DataLoading/EdFi.SmokeTest.Console/Application/CommandLineOverrides.cs
Utilities/DataLoading/EdFi.SmokeTest.Console/Application/SmokeTestConfigurationValidator.cs
Utilities/DataLoading/EdFi.SmokeTest.Console/Application/SmokeTestsConfiguration.cs
Utilities/DataLoading/EdFi.XmlLookup.Console/Application/CommandLineOverrides.cs
Utilities/DataLoading/EdFi.XmlLookup.Console/Application/XmlLookupConfiguration.cs

Adding Support for External Cache Hash Code
Adding Support for Bulk Console
Adding Support to Smoke Test project

Updates to support InstanceYearSpecific ApiMode

---

Application/EdFi.Ods.Common/Models/Resource/ResourceClassBase.cs
Application/EdFi.Ods.Features/OpenApiMetadata/Factories/OpenApiMetadataDefinitionsFactory.cs

Composites mutate ([here](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/blob/66cd7af54d99145b21e8ae2d9ddaeb37b38bbc6a/Application/EdFi.Ods.Features/Composites/CompositeResourceModelBuilder.cs#L112)) the Resource _Properties_ after the Resource is instantiated.
__allPropertiesRaw_ was being initialized during instantiation, meaning it was missing the changes made by Composites. Wrapping it in a Lazy resolves the issue.

[ODS-5654] Composites Open Api metadata doesn't include some properties from the base resource

---

.github/workflows/Packages - EdFi.Ods.CodeGen.yml
.github/workflows/Packages - EdFi.Ods.Minimal.Template.PostgreSQL.yml
.github/workflows/Packages - EdFi.Ods.Minimal.Template.TPDM.PostgreSQL.yml
.github/workflows/Packages - EdFi.Ods.Minimal.Template.TPDM.yml
.github/workflows/Packages - EdFi.Ods.Minimal.Template.yml
.github/workflows/Packages - EdFi.Ods.Populated.Template.PostgreSQL.yml
.github/workflows/Packages - EdFi.Ods.Populated.Template.TPDM.PostgreSQL.yml
.github/workflows/Packages - EdFi.Ods.Populated.Template.TPDM.yml
.github/workflows/Packages - EdFi.Ods.Populated.Template.yml

build error is there  https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/actions/runs/3754286464/jobs/6378373834#step:14:22 in Install-credential-handler step .so https://github.com/Microsoft/artifacts-credprovider#manual-installation-on-windows - Manual Manual installation on Windows
of Microsoft.NuGet.CredentialProvider.zip added

ODS-5704 Install-credential-handler step updated

---

Application/EdFi.Ods.Api/Controllers/DataManagementControllerBase.cs

Tested using Invoke-PostmanIntegrationTests

[ODS-5675] Include basic Request-Response details in the logs

---

.github/workflows/Pkg EdFi.Ods.Minimal.Template.PostgreSQL.yml
.github/workflows/Pkg EdFi.Ods.Minimal.Template.yml

[ODS-5686] Minimal template should include only include descriptors with ed-fi namespace

---

Application/EdFi.Ods.Api/IdentityValueMappers/UniqueIdToUsiValueMapper.cs

Add support for individual person UniqueId/USI lookups to use the read/write connection rather than read-only connection.
See "Developers Only" [comment on ODS-5677](https://tracker.ed-fi.org/browse/ODS-5677?focusedId=72954&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-72954) for explanation and screen shots of the impact of this change.

[ODS-5677] Support for diverting API Read operations to read-only replicas

---

Application/EdFi.Ods.Profiles.Test/EdFi.Ods.Profiles.Test.csproj
Utilities/VisualStudioProjectTemplates/EdFi.ProjectTemplates.Profiles/EdFi.ProjectTemplates.Profiles.csproj
Utilities/VisualStudioProjectTemplates/EdFi.ProjectTemplates.Profiles/Profiles.vstemplate
Utilities/VisualStudioProjectTemplates/EdFi.ProjectTemplates.Profiles/Template_Project.csproj
Utilities/VisualStudioProjectTemplates/EdFi.ProjectTemplates.Profiles/assemblyMetadata.json

Use this documentation for testing release version (..\Ed-Fi-ODS\Utilities\VisualStudioProjectTemplates\EdFi.ProjectTemplates.Installer\bin\Release\EdFi.ProjectTemplates.Installer.vsix) in your local -https://techdocs.ed-fi.org/display/ODSAPIS3V61/Project+Templates+Installation

[ODS-5618] Updated the profile project template

---

Application/EdFi.Ods.Api/Container/Modules/PersistenceModule.cs

Small fix. I did verify that the SuppressStaffCache setting gets read from the config file correctly after the change.

Fix path of SuppressStaffCache setting

---

Application/EdFi.Ods.Api/ExceptionHandling/Translators/DuplicateNaturalKeyUpdateExceptionTranslator.cs
Application/EdFi.Ods.Api/ExceptionHandling/Translators/SqlServer/DuplicateNaturalKeyCreateExceptionTranslator.cs
Application/EdFi.Ods.Api/Security/Authorization/AuthorizationBasisMetadataSelector.cs
Application/EdFi.Ods.Tests/EdFi.Ods.Api/ExceptionHandling/Translators/SqlServer/DuplicateNaturalKeyCreateExceptionTranslatorTests.cs
Application/EdFi.Ods.Tests/EdFi.Ods.Api/ExceptionHandling/Translators/SqlServer/DuplicateNaturalKeyUpdateExceptionTranslatorTests.cs

This updates the API error message referenced in the ticket to follow the proposed format. I searched for other error messages using the same form as the original message but found none.

[ODS-5729] Consider updating API error messages to be more meaningful to the API client 

---

Application/EdFi.Ods.Api/Container/Modules/ApplicationModule.cs
Application/EdFi.Ods.Api/Controllers/DataManagementControllerBase.cs
Application/EdFi.Ods.Api/Extensions/ApplicationBuilderExtensions.cs
Application/EdFi.Ods.Api/Extensions/HttpRequestExtensions.cs
Application/EdFi.Ods.Api/Middleware/RequestResponseDetailsLoggerMiddleware.cs
Application/EdFi.Ods.Api/Startup/OdsStartupBase.cs

Move request/response detail logging from DataManagementControllerBase class to a middleware component

[ODS-5785] Middleware for logging

---

.github/workflows/Pkg EdFi.Database.Admin.yml
.github/workflows/Pkg EdFi.Database.Security.yml

Builds are passing now
https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/actions/runs/4683667133
https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/actions/runs/4683868293

[ODS-5796] Modify builds to support multiple standard versions

---

Application/EdFi.Ods.Api/Container/Modules/ApplicationModule.cs
Application/EdFi.Ods.Api/Startup/OdsStartupBase.cs
Application/EdFi.Ods.Common/Database/DatabaseEngineSpecificStringEqualityComparerProvider.cs
Application/EdFi.Ods.Common/Database/IDatabaseEngineSpecificEqualityComparerProvider.cs
Application/EdFi.Ods.Common/Dependencies/GeneratedArtifactStaticDependencies.cs
Application/EdFi.Ods.Repositories.NHibernate.Tests/StudentProgramAssociationTests.cs
Application/EdFi.Ods.Tests/EdFi.Ods.Common/Database/DatabaseEngineSpecificEqualityProviderTests.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/ApprovalTests.Verify_All.ForScenario.Extensions.Homograph_Models_Entities_Entities.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/ApprovalTests.Verify_All.ForScenario.Extensions.SampleStudentTranscript_Models_Entities_Entities.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/ApprovalTests.Verify_All.ForScenario.Extensions.SampleStudentTransportation_Models_Entities_Entities.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/ApprovalTests.Verify_All.ForScenario.Extensions.Sample_Models_Entities_Entities.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/ApprovalTests.Verify_All.ForScenario.Extensions.TPDM_Models_Entities_Entities.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Mustache/Entities.mustache
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Providers/Impl/ValidatingProfileMetadataProvider.cs

https://dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.Suite3.Ods.WebApi/overview/5.3.1485

[ODS-5781] Update API code to follow default database collation - cqe patch 

---

.github/workflows/Pkg EdFi.Database.Admin.yml
.github/workflows/Pkg EdFi.Database.Security.yml
.github/workflows/Pkg EdFi.Ods.Minimal.Template.yml
.github/workflows/Pkg EdFi.Ods.Populated.Template.TPDM.yml
.github/workflows/Pkg EdFi.Ods.Populated.Template.yml

Once every thing is good , finally I will remove teamcity builds after this PR merge

[ODS-5819] windows-latest build updated to powershell 5.1

---

Application/EdFi.Ods.Api/Security/Authorization/AuthorizationBasisMetadataSelector.cs

Fix the bit value used for the ReadChanges action.

[ODS-5903] Fix the bit value used for the ReadChanges action

---

Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/DataStanadard_400_ApprovalTests.Verify.Extensions.Sample.1.0.0_Std_4.0.0_Models_Mappers_EntityMapper.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/DataStanadard_400_ApprovalTests.Verify.Extensions.SampleStudentTranscript.1.0.0_Std_4.0.0_Models_Entities_Entities.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/DataStanadard_400_ApprovalTests.Verify.Extensions.SampleStudentTranscript.1.0.0_Std_4.0.0_Models_Mappers_EntityMapper.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/DataStanadard_400_ApprovalTests.Verify.Extensions.SampleStudentTransportation.1.0.0_Std_4.0.0_Models_Entities_Entities.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/DataStanadard_400_ApprovalTests.Verify.Extensions.SampleStudentTransportation.1.0.0_Std_4.0.0_Models_Mappers_EntityMapper.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/DataStanadard_400_ApprovalTests.Verify.Extensions.TPDM.1.1.0_Std_4.0.0_Models_Entities_Entities.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/DataStanadard_400_ApprovalTests.Verify.Extensions.TPDM.1.1.0_Std_4.0.0_Models_Mappers_EntityMapper.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/DataStanadard_400_ApprovalTests.cs

This is a follow-on PR for ODS-5907 to the approved output files.

[ODS-5907] Updating approval test files for key value update prevention

---

Application/EdFi.Admin.DataAccess/EdFi.Admin.DataAccess.csproj
Application/EdFi.Ods.Api/EdFi.Ods.Api.csproj
Application/EdFi.Ods.Common/EdFi.Ods.Common.csproj
Application/EdFi.Ods.Features/EdFi.Ods.Features.csproj
Application/EdFi.Ods.Repositories.NHibernate.Tests/EdFi.Ods.Repositories.NHibernate.Tests.csproj
Application/EdFi.Ods.Sandbox/EdFi.Ods.Sandbox.csproj
Application/EdFi.Ods.Tests/EdFi.Ods.Tests.csproj
Application/EdFi.Security.DataAccess/EdFi.Security.DataAccess.csproj
Application/Test.Common/Test.Common.csproj
NOTICES.md
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/EdFi.Ods.CodeGen.Tests.csproj
Utilities/CodeGeneration/EdFi.Ods.CodeGen/EdFi.Ods.CodeGen.csproj
Utilities/DataLoading/EdFi.BulkLoadClient.Console/EdFi.BulkLoadClient.Console.csproj
Utilities/DataLoading/EdFi.LoadTools.Test/EdFi.LoadTools.Test.csproj
Utilities/DataLoading/EdFi.LoadTools/EdFi.LoadTools.csproj
Utilities/DataLoading/EdFi.SmokeTest.Console/EdFi.SmokeTest.Console.csproj
Utilities/DataLoading/EdFi.XmlLookup.Console/EdFi.XmlLookup.Console.csproj
Utilities/GenerateSecurityGraphs/GenerateSecurityGraphs/GenerateSecurityGraphs.csproj
tests/EdFi.Admin.DataAccess.IntegrationTests/EdFi.Admin.DataAccess.IntegrationTests.csproj
tests/EdFi.Admin.DataAccess.UnitTests/EdFi.Admin.DataAccess.UnitTests.csproj
tests/EdFi.Common.UnitTests/EdFi.Common.UnitTests.csproj
tests/EdFi.Ods.Api.IntegrationTests/EdFi.Ods.Api.IntegrationTests.csproj
tests/EdFi.Ods.Features.UnitTests/EdFi.Ods.Features.UnitTests.csproj
tests/EdFi.Ods.WebApi.CompositeSpecFlowTests/EdFi.Ods.WebApi.CompositeSpecFlowTests.csproj
tests/EdFi.Ods.WebApi.IntegrationTests/EdFi.Ods.WebApi.IntegrationTests.csproj
tests/EdFi.Security.DataAccess.UnitTests/EdFi.Security.DataAccess.UnitTests.csproj

Updated NOTICES.md file
Removed unused references

[ODS-5754] Update License Notices and Cleanup Unsued References

---

Application/EdFi.Ods.Api/Security/Authorization/PersonResourceGraphAuthorizationTransformer.cs

This updates `PersonResourceLoadGraphTransformer` so that it supports the renaming of Parent to Contact in Ed-Fi Standard v5 in addition to supporting data standard v4.

[ODS-5972] Dependency metadata transformations for authorization concerns do not support Contact in Ed-Fi Standard v5

---

.github/workflows/Trgr InitDev workflows in Implementation repo.yml

https://github.com/Codex-/return-dispatch/blob/main/src/api.ts#L72 return-dispatch Action does not allow special character () in workflow name , So I renamed 3 workflows in ODS Implementation PR here https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/pull/829/files .   Once reviewed both PR and first get ODS Implementation PR get merged and then we need to re-run https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/blob/main/.github/workflows/Trgr%20InitDev%20workflows%20in%20Implementation%20repo.yml again to get green in this repo

[ODS-6043]Implementation Trigger builds from the ODS repo

---

Utilities/VisualStudioProjectTemplates/EdFi.ProjectTemplates.Extensions/Template_Project.csproj

To Test:
1. In Visual Studio Extensions > Manage Extensions > Installed > Templates. "Uninstall" previous versions of "Ed-Fi Alliance Project Templates"
2. Build Utilities\EdFi.ProjectTemplates.sln in Release mode
3. Install the .VSIX from the EdFi.ProjectTemplates.Installer project bin directory.
4. [Create an extension project](https://techdocs.ed-fi.org/pages/viewpage.action?pageId=149587472#HowTo:ExtendtheEdFiODS/APIStudentTransportationExample-Step4.CreateExtensionProjectinODS/APISolution) and verify the .csproj file matches the sample extension project
5. Verify no errors running and accessing extension entities. 
After this is approved we will need to update the download link here: https://techdocs.ed-fi.org/display/ODSAPIS3V70/Project+Templates+Installation

[ODS-6080] Modifications to Template_Project.csproj

---

Postman Test Suite/Ed-Fi ODS-API Integration Test Suite AuthorizationTests.postman_collection.json

[ODS-6082] Add PostmanTest coverage for role named program in programEvaluation domain

---

Application/EdFi.Admin.DataAccess/EdFi.Admin.DataAccess.csproj
Application/EdFi.Common/EdFi.Common.csproj
Application/EdFi.Ods.Api/EdFi.Ods.Api.csproj
Application/EdFi.Ods.Common/EdFi.Ods.Common.csproj
Application/EdFi.Ods.Profiles.Test/EdFi.Ods.Profiles.Test.csproj
Application/EdFi.Ods.Repositories.NHibernate.Tests/EdFi.Ods.Repositories.NHibernate.Tests.csproj
Application/EdFi.Ods.Sandbox/EdFi.Ods.Sandbox.csproj
Application/EdFi.Ods.Standard/EdFi.Ods.Standard.csproj
Application/EdFi.Ods.Tests/EdFi.Ods.Tests.csproj
Application/EdFi.Security.DataAccess/EdFi.Security.DataAccess.csproj
Application/EdFi.TestObjects/EdFi.TestObjects.csproj
Application/Test.Common/Test.Common.csproj
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/EdFi.Ods.CodeGen.Tests.csproj
Utilities/CodeGeneration/EdFi.Ods.CodeGen/EdFi.Ods.CodeGen.csproj
Utilities/DataLoading/EdFi.BulkLoadClient.Console/EdFi.BulkLoadClient.Console.csproj
Utilities/DataLoading/EdFi.LoadTools.Test/EdFi.LoadTools.Test.csproj
Utilities/DataLoading/EdFi.LoadTools/EdFi.LoadTools.csproj
Utilities/DataLoading/EdFi.SmokeTest.Console/EdFi.SmokeTest.Console.csproj
Utilities/DataLoading/EdFi.XmlLookup.Console/EdFi.XmlLookup.Console.csproj
Utilities/GenerateSecurityGraphs/GenerateSecurityGraphs/GenerateSecurityGraphs.csproj
Utilities/SdkGen/EdFi.SdkGen.Console/EdFi.SdkGen.Console.csproj
Utilities/VisualStudioProjectTemplates/EdFi.ProjectTemplates.Profiles/Template_Project.csproj
tests/EdFi.Admin.DataAccess.UnitTests/EdFi.Admin.DataAccess.UnitTests.csproj
tests/EdFi.Ods.Api.IntegrationTests/EdFi.Ods.Api.IntegrationTests.csproj
tests/EdFi.Ods.WebApi.CompositeSpecFlowTests/EdFi.Ods.WebApi.CompositeSpecFlowTests.csproj
tests/EdFi.Ods.WebApi.IntegrationTests/EdFi.Ods.WebApi.IntegrationTests.csproj
tests/EdFi.Security.DataAccess.UnitTests/EdFi.Security.DataAccess.UnitTests.csproj

Package published EdFi.Suite3.Ods.SandboxAdmin.5.3.1490.nupkg
EdFi.Suite3.Ods.SwaggerUI.5.3.1490.nupkg
EdFi.Suite3.Ods.WebApi.5.3.1490.nupkg
EdFi.Suite3.Ods.WebApi.Prerelease.5.3.1490.nupkg
EdFi.Suite3.RestApi.Databases.5.3.1490.nupkg

[ODS-6093] 5.3-cqe Update package dependencies to avoid security vulnerabilities

---

.github/workflows/Lib edFi.admin.dataaccess manual.yml
.github/workflows/Lib edFi.common manual.yml
.github/workflows/Lib edFi.loadtools manual.yml
.github/workflows/Lib edFi.ods.api manual.yml
.github/workflows/Lib edFi.ods.common manual.yml
.github/workflows/Lib edFi.ods.standard manual.yml
.github/workflows/Lib edFi.security.dataaccess manual.yml
.github/workflows/Pkg EdFi.Database.Admin.yml
.github/workflows/Pkg EdFi.Database.Security.yml
.github/workflows/Pkg EdFi.Ods.CodeGen.yml
.github/workflows/Pkg EdFi.Ods.Minimal.Template.PostgreSQL.yml
.github/workflows/Pkg EdFi.Ods.Minimal.Template.TPDM.PostgreSQL.yml
.github/workflows/Pkg EdFi.Ods.Minimal.Template.TPDM.yml
.github/workflows/Pkg EdFi.Ods.Minimal.Template.yml
.github/workflows/Pkg EdFi.Ods.Populated.Template.PostgreSQL.yml
.github/workflows/Pkg EdFi.Ods.Populated.Template.TPDM.PostgreSQL.yml
.github/workflows/Pkg EdFi.Ods.Populated.Template.TPDM.yml
.github/workflows/Pkg EdFi.Ods.Populated.Template.yml
.github/workflows/Trgr InitDev workflows in Implementation repo.yml

github.run_number  will be different in each developer's fork Hence So package number is getting in minus number ,so added new step to reset  to 1 if gets minus for BUILD_INCREMENTER ,so that it will work in Fork also

[ODS-6083] Setup Ed-Fi-ODS in Developer's Fork

---

Application/EdFi.Common/Security/ApiClientAuthenticator.cs
Application/EdFi.Ods.Api/Security/Authentication/ApiClientDetailsProvider.cs
Application/EdFi.Ods.Tests/EdFi.Ods.Api/Authentication/ApiClientDetailsProviderTests.cs
Postman Test Suite/Ed-Fi ODS-API Integration Test Suite.postman_collection.json

…e (#615)
* authenticate fails for  non-existing key with 401 status code
* codefix for adding ArgumentNull Exception

[ODS-6259] Cherry-Pick ODS-5670 into main/6x - Key/secret authentication fails with 500 status when non-existing key is supplied

---

Application/EdFi.Ods.Api/Caching/InstanceSecurityRepositoryCache.cs
Application/EdFi.Ods.Api/EdFi.Ods.Api.csproj

Fix EFCore runtime breaking changes.

[ODS-6257] Fix InstanceSecurityRepositoryCache

---

Utilities/GenerateSecurityGraphs/GenerateSecurityGraphs/Program.cs

Added the equivalent changes made in [ODS-6175](https://tracker.ed-fi.org/browse/ODS-6175).

[ODS-6192] GenerateSecurityGraphs update connection parameters 

---

.github/workflows/Pkg EdFi.Ods.Minimal.Template.PostgreSQL.yml
.github/workflows/Pkg EdFi.Ods.Minimal.Template.yml
Utilities/CodeGeneration/README.md
Utilities/VisualStudioProjectTemplates/EdFi.ProjectTemplates.Extensions/EdFi.Ods.Extensions.ExtensionName.nuspec

Include changes on nuspec file for visualStudioProjectTemplate: net6 to net8

[ODS-6262] Cherry-Pick ODS-5686 into main6x - Minimal template should include only include descriptors

---

.github/workflows/Pkg EdFi.Database.Admin.yml
.github/workflows/Pkg EdFi.Database.Security.yml
.github/workflows/Pkg EdFi.ProjectTemplates.Installer.yml
Application/EdFi.Ods.Api/Startup/OdsStartupBase.cs
Utilities/CodeGeneration/README.md
Utilities/VisualStudioProjectTemplates/EdFi.ProjectTemplates.Composites/EdFi.ProjectTemplates.Composites.csproj
Utilities/VisualStudioProjectTemplates/EdFi.ProjectTemplates.Extensions/EdFi.ProjectTemplates.Extensions.csproj
Utilities/VisualStudioProjectTemplates/EdFi.ProjectTemplates.Installer/EdFi.ProjectTemplates.Installer.csproj
Utilities/VisualStudioProjectTemplates/EdFi.ProjectTemplates.Installer/EdFi.ProjectTemplates.Installer.nuspec
Utilities/VisualStudioProjectTemplates/EdFi.ProjectTemplates.Installer/source.extension.vsixmanifest
Utilities/VisualStudioProjectTemplates/EdFi.ProjectTemplates.Profiles/EdFi.ProjectTemplates.Profiles.csproj
build.githubactions.ps1

https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-Actions/pull/79
Needs Approval for this PR also

[ODS-6195] Pkg EdFi.ProjectTemplates.Installer Added

---

Application/EdFi.Admin.DataAccess/Repositories/ClientAppRepo.cs

[ODS-6377] Sandbox Refresh fails

---

Application/EdFi.Ods.Common/Extensions/IExtensionsSynchronizationSourceSupport.cs
Application/EdFi.Ods.Common/Extensions/IHasExtensionsExtensions.cs
Application/EdFi.Ods.Tests/EdFi.Ods.Common/IHasExtensionsExtensionsTests.cs
Postman Test Suite/Ed-Fi ODS-API Integration Test Suite.postman_collection.json
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/ApprovalTests.Verify_All.ForScenario.Extensions.SampleStudentTranscript_Models_Mappers_EntityMapper.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/ApprovalTests.Verify_All.ForScenario.Extensions.Sample_Models_Mappers_EntityMapper.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/ApprovalTests.Verify_All.ForScenario.Extensions.TPDM_Models_Mappers_EntityMapper.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/ApprovalTests.Verify_All.ForScenario.Profiles.Sample_Resources_Resources.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Mustache/Entities.mustache
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Mustache/EntityMapper.mustache
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Mustache/Resources.mustache

I'm bringing a subset of changes initially implemented in [PR 638](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/pull/638) (except for the Postman tests; those are new).

[ODS-6346] Extension not getting properly updated with NULL values - v6

---

Application/EdFi.Ods.Common/Extensions/IExtensionsSynchronizationSourceSupport.cs
Application/EdFi.Ods.Common/Extensions/IHasExtensionsExtensions.cs
Application/EdFi.Ods.Tests/EdFi.Ods.Common/IHasExtensionsExtensionsTests.cs
Postman Test Suite/Ed-Fi ODS-API Integration Test Suite.postman_collection.json
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/ApprovalTests.Verify_All.ForScenario.Extensions.SampleStudentTranscript_Models_Mappers_EntityMapper.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/ApprovalTests.Verify_All.ForScenario.Extensions.Sample_Models_Mappers_EntityMapper.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/ApprovalTests.Verify_All.ForScenario.Extensions.TPDM_Models_Mappers_EntityMapper.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/ApprovalTests.Verify_All.ForScenario.Profiles.Sample_Resources_Resources.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Mustache/Entities.mustache
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Mustache/EntityMapper.mustache
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Mustache/Resources.mustache

Cherry-pick of the changes made in [PR 1073](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/pull/1073).

[ODS-6346] Extension not getting properly updated with NULL values - v5

---

Postman Test Suite/Ed-Fi ODS-API Integration Test Suite.postman_collection.json

Given that the issue was fixed in v7.0, I'm just adding Postman Tests to prevent regressions.

[ODS-6346] Extension not getting properly updated with NULL values

---

Application/EdFi.Ods.Common/Extensions/ValidatorExtensions.cs
Application/EdFi.Ods.Tests/EdFi.Ods.Common/Extensions/ValidationExtensionsTests.cs

Getting Incomplete Validation Message for Bad Descriptor Reference for some resources - v5.4
Clone of ODS-5070
Cherry picked commit 109e1b4a871fc6e6d45167b8720f7464676fadbe to apply bug fix to v5.4 that was applied to v6.0

ODS-6247 - Getting Incomplete Validation Message for Bad Descriptor Reference for some resources - v5.4

---

Application/EdFi.Ods.Api/Models/GraphML/ResourceLoadOrder.cs
Application/EdFi.Ods.Features/Controllers/AggregateDependencyController.cs
tests/EdFi.Ods.WebApi.IntegrationTests/Sandbox/Controllers/AggregateDependencyControllerTests.Should_Get_Dependencies.approved.txt

Cherry-picked #407 to bring the fix to the upcoming v5.4 release.

[ODS-6443] Dependency order endpoints don't list update order - v5.4

---

.github/workflows/Cleanup Caches by a branch.yml
.github/workflows/CodeQL Security Scan.yml
.github/workflows/Dependencies Security Scan.yml
.github/workflows/Find Standard and Extension Versions.yml
.github/workflows/Lib edFi.admin.dataaccess.yml
.github/workflows/Lib edFi.common.yml
.github/workflows/Lib edFi.loadtools.yml
.github/workflows/Lib edFi.ods.api.yml
.github/workflows/Lib edFi.ods.common.yml
.github/workflows/Lib edFi.ods.standard.yml
.github/workflows/Lib edFi.security.dataaccess.yml
.github/workflows/Pkg EdFi.Ods.CodeGen.yml
.github/workflows/Pkg EdFi.Ods.Minimal.Template.PostgreSQL.yml
.github/workflows/Pkg EdFi.Ods.Minimal.Template.TPDM.PostgreSQL.yml
.github/workflows/Pkg EdFi.Ods.Minimal.Template.TPDM.yml
.github/workflows/Pkg EdFi.Ods.Minimal.Template.yml
.github/workflows/Pkg EdFi.Ods.Populated.Template.PostgreSQL.yml
.github/workflows/Pkg EdFi.Ods.Populated.Template.TPDM.PostgreSQL.yml
.github/workflows/Pkg EdFi.Ods.Populated.Template.TPDM.yml
.github/workflows/Pkg EdFi.Ods.Populated.Template.yml
.github/workflows/Scorecard supply-chain security.yml
.github/workflows/Security Vulnerability Check on Release Tags.yml
.github/workflows/Trgr InitDev workflows in Implementation repo.yml
Utilities/SdkGen/EdFi.SdkGen.Console/EdFi.OdsApi.Sdk.nuspec
build.githubactions.ps1
tests/EdFi.Ods.Api.IntegrationTests/EducationOrganizationTestDataBuilder.cs

The "Pkg EdFi.ProjectTemplates.Installer" check fails because it pulls the main branch from the Ed-Fi-ODS-Implementation repository. Please ensure it completes successfully after merging the corresponding PR in Ed-Fi-ODS-Implementation.

[ODS-6530] Switch Ubuntu builds back to Ubuntu latest (24.04)

---

Utilities/Directory.Build.props

we already branch for b-v7.2-patch1 with fix of upgrading to 5.5.2 in ODS and ODS Implementation repos .
b-v7.1-patch2 also have fix of upgrading to 5.5.2 in ODS and ODS Implementation repos .
I will create new ticket for actual release of both patches after this ticket is merged

[ODS-6570] Nhibernate Upgrade for 7.1 and 7.2

---

Artifacts/MsSql/Structure/Admin/0177-Add-Unique-Constraint-Profiles.sql
Artifacts/PgSql/Structure/Admin/0177-Add-Unique-Constraint-Profiles.sql

The Admin database changes associated with the ODS-6602 PR #1205.

[ODS-6602] Database changes - API only allows tenant1's profiles when different profiles are set up for different tenants

---

Application/EdFi.Admin.DataAccess/Models/Application.cs
Application/EdFi.Admin.DataAccess/Repositories/ClientAppRepo.cs
Application/EdFi.Admin.DataAccess/Repositories/IClientAppRepo.cs
Application/EdFi.Ods.Api/EdFi.Ods.Api.csproj
Application/EdFi.Ods.Sandbox/EdFi.Ods.Sandbox.csproj
Application/EdFi.Ods.Tests/EdFi.Ods.Tests.csproj
tests/EdFi.Ods.WebApi.CompositeSpecFlowTests/EdFi.Ods.WebApi.CompositeSpecFlowTests.csproj
tests/EdFi.Ods.WebApi.IntegrationTests/EdFi.Ods.WebApi.IntegrationTests.csproj

[ODS-6639] Sandbox Admin for Certification Testing

---

Postman Test Suite/Ed-Fi ODS-API Integration Test Suite.postman_collection.json
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/4.0.0/DataStandard_400_ApprovalTests.Verify.Extensions.Sample.1.0.0_Std_4.0.0_EntityOrmMappings_MsSql_EntityOrmMappings.generated.hbm.approved.xml
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/4.0.0/DataStandard_400_ApprovalTests.Verify.Extensions.Sample.1.0.0_Std_4.0.0_EntityOrmMappings_PgSql_EntityOrmMappings.generated.hbm.approved.xml
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/4.0.0/DataStandard_400_ApprovalTests.Verify.Extensions.Sample.1.0.0_Std_4.0.0_ExceptionHandling_DatabaseMetadata.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/4.0.0/DataStandard_400_ApprovalTests.Verify.Extensions.Sample.1.0.0_Std_4.0.0_Models_Entities_Entities.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/4.0.0/DataStandard_400_ApprovalTests.Verify.Extensions.Sample.1.0.0_Std_4.0.0_Models_Interfaces_EntityInterfaces.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/4.0.0/DataStandard_400_ApprovalTests.Verify.Extensions.Sample.1.0.0_Std_4.0.0_Models_Mappers_EntityMapper.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/4.0.0/DataStandard_400_ApprovalTests.Verify.Extensions.Sample.1.0.0_Std_4.0.0_Resources_Resources.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/5.2.0/DataStandard_520_ApprovalTests.Verify.Extensions.Sample.1.0.0_Std_5.2.0_EntityOrmMappings_MsSql_EntityOrmMappings.generated.hbm.approved.xml
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/5.2.0/DataStandard_520_ApprovalTests.Verify.Extensions.Sample.1.0.0_Std_5.2.0_EntityOrmMappings_PgSql_EntityOrmMappings.generated.hbm.approved.xml
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/5.2.0/DataStandard_520_ApprovalTests.Verify.Extensions.Sample.1.0.0_Std_5.2.0_ExceptionHandling_DatabaseMetadata.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/5.2.0/DataStandard_520_ApprovalTests.Verify.Extensions.Sample.1.0.0_Std_5.2.0_Models_Entities_Entities.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/5.2.0/DataStandard_520_ApprovalTests.Verify.Extensions.Sample.1.0.0_Std_5.2.0_Models_Interfaces_EntityInterfaces.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/5.2.0/DataStandard_520_ApprovalTests.Verify.Extensions.Sample.1.0.0_Std_5.2.0_Models_Mappers_EntityMapper.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/5.2.0/DataStandard_520_ApprovalTests.Verify.Extensions.Sample.1.0.0_Std_5.2.0_Resources_Resources.generated.approved.cs

Removes redundant Id property, and uses BusReference instead

[DMS-610] Update Sample.BusReference Entity

---

Postman Test Suite/Ed-Fi ODS-API Integration Test Suite GetByExample Tests.postman_collection.json
Postman Test Suite/Ed-Fi ODS-API Integration Test Suite.postman_collection.json
Postman Test Suite/Ed-Fi ODS-API Profile Test Suite.postman_collection.json
Postman Test Suite/Multitenancy/Ed-Fi ODS-API Multi-Tenancy.postman_collection.json

Update to use sample extension instead of TPDM

[ODS-6668] Remove TPDM usages from Postman tests

---

Application/EdFi.Ods.Common/Infrastructure/Listeners/EdFiOdsPostUpdateEventListener.cs
Application/EdFi.Ods.Common/Infrastructure/Listeners/EdFiOdsPreInsertListener.cs
Application/EdFi.Ods.Common/Infrastructure/Listeners/EdFiOdsPreUpdateListener.cs
Application/EdFi.Ods.Common/Infrastructure/Listeners/KeyChangeHelper.cs
Application/EdFi.Ods.Common/Infrastructure/Repositories/GetEntitiesByIds.cs
Application/EdFi.Ods.Common/Models/Domain/EntityProperty.cs
Application/EdFi.Ods.Common/Repositories/EntityDeserializer.cs
Application/EdFi.Ods.Features/SerializedData/Repositories/ReferenceDataResolver.cs
Application/EdFi.Ods.Standard/Standard/4.0.0/Artifacts/MsSql/Structure/Ods/Changes/0210-CreateTriggersForChangeVersionAndKeyChanges.sql
Application/EdFi.Ods.Standard/Standard/4.0.0/Artifacts/PgSql/Structure/Ods/Changes/0020-CreateChangeVersionSequence.sql
Application/EdFi.Ods.Standard/Standard/5.2.0/Artifacts/MsSql/Structure/Ods/Changes/0210-CreateTriggersForChangeVersionAndKeyChanges.sql
Application/EdFi.Ods.Standard/Standard/5.2.0/Artifacts/PgSql/Structure/Ods/Changes/0020-CreateChangeVersionSequence.sql
Postman Test Suite/Ed-Fi ODS-API ChangeQueries Key Changes and Deletes Test Suite.postman_collection.json
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/4.0.0/DataStandard_400_ApprovalTests.Verify.Extensions.Homograph.1.0.0_Std_4.0.0_Models_Entities_Entities.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/4.0.0/DataStandard_400_ApprovalTests.Verify.Extensions.Sample.1.0.0_Std_4.0.0_Models_Entities_Entities.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/4.0.0/DataStandard_400_ApprovalTests.Verify.Extensions.SampleStudentTranscript.1.0.0_Std_4.0.0_Models_Entities_Entities.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/4.0.0/DataStandard_400_ApprovalTests.Verify.Extensions.TPDM.1.1.0_Std_4.0.0_Models_Entities_Entities.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/5.2.0/DataStandard_520_ApprovalTests.Verify.Extensions.Homograph.1.0.0_Std_5.2.0_Models_Entities_Entities.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/5.2.0/DataStandard_520_ApprovalTests.Verify.Extensions.Sample.1.0.0_Std_5.2.0_Models_Entities_Entities.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/5.2.0/DataStandard_520_ApprovalTests.Verify.Extensions.SampleStudentTranscript.1.0.0_Std_5.2.0_Models_Entities_Entities.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen.Tests/Approval/5.2.0/DataStandard_520_ApprovalTests.Verify.Extensions.TPDM.1.1.0_Std_5.2.0_Models_Entities_Entities.generated.approved.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Generators/Entities.cs
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Mustache/Entities.mustache
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Mustache/Entities_PropertyAccessors.mustache
Utilities/CodeGeneration/EdFi.Ods.CodeGen/Mustache/Entities_PropertyAccessors_ReferenceData.mustache

Merge this branch with a ❗❗MERGE ONLY❗❗ (NO SQUASH). The commits have already been squashed and retain the descriptions for the tickets for visibility into the changes for each ticket.
NOTE: This branch contains individual commits for [ODS-6675](https://edfi.atlassian.net/browse/ODS-6675), [ODS-6681](https://edfi.atlassian.net/browse/ODS-6681) and [ODS-6682](https://edfi.atlassian.net/browse/ODS-6682).
[ODS-6675]: https://edfi.atlassian.net/browse/ODS-6675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ODS-6681]: https://edfi.atlassian.net/browse/ODS-6681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ODS-6682]: https://edfi.atlassian.net/browse/ODS-6682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …

[ODS-6682] Resource child item references that have key unification result in unresolvable links

---

Application/EdFi.Admin.DataAccess/EdFi.Admin.DataAccess.csproj
Application/EdFi.Common/Security/PackedHashConverter.cs
Application/EdFi.Ods.Api/EdFi.Ods.Api.csproj
Application/EdFi.Ods.Common/EdFi.Ods.Common.csproj
Application/EdFi.Ods.Common/Serialization/Int64Converter.cs
Application/EdFi.Ods.Repositories.NHibernate.Tests/EdFi.Ods.Repositories.NHibernate.Tests.csproj
Application/EdFi.Ods.Sandbox/EdFi.Ods.Sandbox.csproj
Application/EdFi.Ods.Tests/EdFi.Ods.Common/Serialization/Int64ConverterTests.cs
Application/EdFi.Ods.Tests/EdFi.Ods.Tests.csproj
Application/EdFi.Security.DataAccess/EdFi.Security.DataAccess.csproj
tests/EdFi.Admin.DataAccess.UnitTests/EdFi.Admin.DataAccess.UnitTests.csproj
tests/EdFi.Common.UnitTests/Security/PackedHashConverterTests.cs
tests/EdFi.Ods.WebApi.CompositeSpecFlowTests/EdFi.Ods.WebApi.CompositeSpecFlowTests.csproj
tests/EdFi.Ods.WebApi.IntegrationTests/EdFi.Ods.WebApi.IntegrationTests.csproj
tests/EdFi.Security.DataAccess.UnitTests/EdFi.Security.DataAccess.UnitTests.csproj

This PR brings ODS-6685 and ODS-6663 to patch branch and updates EdFi.Suite3.Common, EdFi.Suite3.Admin.DataAccess, and EdFi.Suite3.Security.DataAccess packages

[ODS-6687] Release ODS API v7.3 patch2
